import { useEffect,useState } from 'react';
import { Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from 'react-native';
import { supabase } from '../lib/supabase';
export default function Iza(){
 const [campaigns,setCampaigns]=useState<any[]>([]),[mine,setMine]=useState<Map<string,string>>(new Map());
 async function load(){const [a,b]=await Promise.all([supabase.rpc('public_active_iza_campaigns'),supabase.rpc('customer_my_iza')]);setCampaigns(a.data||[]);setMine(new Map((b.data||[]).map((x:any)=>[x.iza_campaign_id,x.intent_status])))}
 useEffect(()=>{load()},[]);
 async function vote(id:string,v:'in'|'out'){const {error}=await supabase.rpc('customer_set_iza_response',{p_iza_campaign_id:id,p_response:v});if(error)return Alert.alert('WENIK',error.message);load()}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.title}>IZA</Text><Text style={s.sub}>I’m in / I’m out</Text>
 {campaigns.map(x=>{const v=mine.get(x.iza_campaign_id);return <View key={x.iza_campaign_id} style={s.card}><View style={s.top}><Text style={s.eye}>CONDITIONAL DEMAND</Text><Text style={s.badge}>IZA</Text></View><Text style={s.name}>{x.title||x.product_name}</Text><Text style={s.desc}>{x.condition_text||''}</Text>{x.target_price!=null?<Text style={s.price}>${Number(x.target_price).toFixed(2)}</Text>:null}<View style={s.choices}><Pressable onPress={()=>vote(x.iza_campaign_id,'in')} style={[s.btn,v==='in'&&s.on]}><Text style={s.btnText}>I'M IN</Text></Pressable><Pressable onPress={()=>vote(x.iza_campaign_id,'out')} style={[s.btn,s.out,v==='out'&&s.on]}><Text style={s.btnText}>I'M OUT</Text></Pressable></View></View>})}
 {!campaigns.length?<View style={s.card}><Text style={s.desc}>No active IZA.</Text></View>:null}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#09090d'},page:{padding:20},title:{color:'#fff',fontSize:30,fontWeight:'900'},sub:{color:'#aaaab5',marginTop:4,marginBottom:18},card:{backgroundColor:'#17131f',borderRadius:22,padding:18,marginBottom:12},top:{flexDirection:'row',justifyContent:'space-between'},eye:{color:'#ff7a00',fontSize:10,fontWeight:'900'},badge:{color:'#ffd43b',fontWeight:'900'},name:{color:'#fff',fontSize:21,fontWeight:'900',marginTop:8},desc:{color:'#aaaab5',marginTop:6,lineHeight:19},price:{color:'#ffd43b',fontSize:24,fontWeight:'900',marginTop:12},choices:{flexDirection:'row',gap:10,marginTop:16},btn:{flex:1,backgroundColor:'#292331',padding:14,borderRadius:16,alignItems:'center'},out:{backgroundColor:'#201b25'},on:{backgroundColor:'#ef159d'},btnText:{color:'#fff',fontWeight:'900'}});
