import { useEffect,useState } from 'react';
import { Alert,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { supabase } from '../lib/supabase';
export default function Iza(){
 const [campaigns,setCampaigns]=useState<any[]>([]),[mine,setMine]=useState<Map<string,string>>(new Map()),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true);
 async function load(){const [a,b]=await Promise.all([supabase.rpc('public_active_iza_campaigns'),supabase.rpc('customer_my_iza')]);setCampaigns(a.data||[]);setMine(new Map((b.data||[]).map((x:any)=>[x.iza_campaign_id,x.intent_status])));setLoading(false)}
 useEffect(()=>{load()},[]);
 async function vote(id:string,v:'in'|'out'){setBusy(id);const {error}=await supabase.rpc('customer_set_iza_response',{p_iza_campaign_id:id,p_response:v});setBusy('');if(error)return Alert.alert('WENIK',error.message);load()}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><LinearGradient colors={['#b978f3','#f58bc5','#ffad86']} style={s.hero}><Text style={s.heroEye}>IZA | إذا</Text><Text style={s.heroTitle}>If the deal works… decide.</Text><Text style={s.heroSub}>Choose I’M IN or I’M OUT. You can change your mind.</Text></LinearGradient>
 <View style={s.sectionHead}><View><Text style={s.section}>ACTIVE IZA</Text><Text style={s.sectionSub}>One decision. One tap.</Text></View><Text style={s.count}>{campaigns.length} ACTIVE</Text></View>
 {loading?<View style={s.card}><Text style={s.desc}>Loading IZA…</Text></View>:campaigns.map(x=>{const v=mine.get(x.iza_campaign_id);return <View key={x.iza_campaign_id} style={s.card}><View style={s.top}><Text style={s.eye}>CONDITIONAL DEMAND</Text><Text style={s.badge}>IZA</Text></View><Text style={s.name}>{x.title||x.product_name}</Text><Text style={s.desc}>{x.condition_text||''}</Text>{x.target_price!=null?<Text style={s.price}>${Number(x.target_price).toFixed(2)}</Text>:null}{v?<View style={s.current}><Text style={s.currentLabel}>YOUR CHOICE</Text><Text style={s.currentValue}>{v==='in'?"I’M IN":"I’M OUT"}</Text><Text style={s.currentHint}>You can change your mind anytime.</Text></View>:null}<View style={s.choices}><Pressable disabled={busy===x.iza_campaign_id} onPress={()=>vote(x.iza_campaign_id,'in')} style={[s.btn,v==='in'&&s.on]}><Text style={s.btnText}>{busy===x.iza_campaign_id?'WAIT…':v==='in'?'✓ I’M IN':"I'M IN"}</Text></Pressable><Pressable disabled={busy===x.iza_campaign_id} onPress={()=>vote(x.iza_campaign_id,'out')} style={[s.btn,s.out,v==='out'&&s.on]}><Text style={s.btnText}>{busy===x.iza_campaign_id?'WAIT…':v==='out'?'✓ I’M OUT':"I'M OUT"}</Text></Pressable></View></View>})}
 {!loading&&!campaigns.length?<View style={s.empty}><Text style={s.emptyTitle}>NO ACTIVE IZA</Text><Text style={s.desc}>New decisions will appear here when they go live.</Text></View>:null}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7fb'},page:{padding:14,paddingBottom:110},hero:{padding:20,borderRadius:24,marginBottom:14},heroEye:{color:'#fff',fontSize:10,fontWeight:'900',letterSpacing:2},heroTitle:{color:'#fff',fontSize:26,fontWeight:'900',marginTop:5},heroSub:{color:'rgba(255,255,255,.9)',fontSize:12,marginTop:5,lineHeight:18},sectionHead:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',marginTop:6,marginBottom:10},section:{color:'#8f24ff',fontSize:12,fontWeight:'900',letterSpacing:1.4},sectionSub:{color:'#77717e',fontSize:11,marginTop:3},count:{color:'#99929f',fontSize:9,fontWeight:'900'},card:{backgroundColor:'#fff',borderRadius:22,padding:18,marginBottom:12,borderWidth:1,borderColor:'rgba(92,55,110,.08)'},top:{flexDirection:'row',justifyContent:'space-between'},eye:{color:'#ff6f21',fontSize:10,fontWeight:'900'},badge:{color:'#ffd21c',fontWeight:'900'},name:{color:'#18141d',fontSize:21,fontWeight:'900',marginTop:8},desc:{color:'#77717e',marginTop:6,lineHeight:19},price:{color:'#8f24ff',fontSize:24,fontWeight:'900',marginTop:12},current:{backgroundColor:'#f8f2ff',borderRadius:15,padding:12,marginTop:14,flexDirection:'row',alignItems:'center',gap:8},currentLabel:{color:'#99929f',fontSize:8,fontWeight:'900',letterSpacing:.8},currentValue:{color:'#8f24ff',fontSize:11,fontWeight:'900'},currentHint:{color:'#77717e',fontSize:8,marginLeft:'auto'},choices:{flexDirection:'row',gap:10,marginTop:12},btn:{flex:1,backgroundColor:'#8f24ff',padding:14,borderRadius:16,alignItems:'center'},out:{backgroundColor:'#ef159d'},on:{backgroundColor:'#ff6f21'},btnText:{color:'#fff',fontWeight:'900'},empty:{backgroundColor:'#fff',borderRadius:22,padding:24,alignItems:'center'},emptyTitle:{color:'#8f24ff',fontSize:12,fontWeight:'900',letterSpacing:1}});
