import { useEffect,useMemo,useState } from 'react';
import { Alert,Linking,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { supabase } from '../lib/supabase';
export default function Me(){
 const [profile,setProfile]=useState<any>(null),[points,setPoints]=useState<number|null>(null),[activity,setActivity]=useState<any[]>([]),[inbox,setInbox]=useState<any[]>([]),[q,setQ]=useState(''),[purchaseVisible,setPurchaseVisible]=useState(20),[notificationVisible,setNotificationVisible]=useState(20);
 async function load(){const [p,b,a,i]=await Promise.all([supabase.rpc('customer_my_profile'),supabase.rpc('wenik_customer_points_balance'),supabase.rpc('customer_my_activity',{p_limit:60}),supabase.rpc('customer_my_inbox',{p_limit:50})]);setProfile(Array.isArray(p.data)?p.data[0]:p.data);if(!b.error)setPoints(Number(b.data??0));setActivity(a.data||[]);setInbox(i.data||[])}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>activity.filter(x=>{const h=String([x.partner_name,x.original_amount,x.final_amount].join(' ')).toLowerCase();return !q||h.includes(q.toLowerCase())}),[activity,q]);
 useEffect(()=>{setPurchaseVisible(20)},[q]);
 async function openMessage(x:any){if(!x.seen_at){await supabase.rpc('customer_open_message',{p_message_id:x.message_id});load()}const url=x.cta_url||x.deep_link||x.url;if(url){const target=String(url).trim();try{const ok=await Linking.canOpenURL(target);if(ok)await Linking.openURL(target);else Alert.alert('WENIK','This link is not available on this device.')}catch{Alert.alert('WENIK','Could not open this link.')}}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
  <LinearGradient colors={['#b978f3','#f58bc5','#ffad86']} style={s.hero}><View style={s.heroLine}/><Text style={s.eye}>YOUR WENIK</Text><Text style={s.title}>{[profile?.first_name,profile?.last_name].filter(Boolean).join(' ')||'Me'}</Text><Text style={s.sub}>{profile?.mobile||profile?.phone||'Your account, activity and notifications.'}</Text></LinearGradient>
  <View style={s.profile}><View style={s.memberTop}><View style={s.avatar}><Text style={s.avatarText}>{String(profile?.first_name||'W').slice(0,1).toUpperCase()}</Text></View><View style={s.memberInfo}><Text style={s.name}>{[profile?.first_name,profile?.last_name].filter(Boolean).join(' ')||'WENIK Member'}</Text><Text style={s.memberId}>{profile?.wenik_id||profile?.customer_wenik_id||'WENIK MEMBER'}</Text></View></View><LinearGradient colors={['#f4e8ff','#fff0f8','#fff1e7']} style={s.pointsCard}><View><Text style={s.pointsLabel}>MY POINTS</Text><Text style={s.points}>{Number(points??0).toLocaleString()}</Text></View><Text style={s.pointsReady}>READY FOR REWARDS</Text></LinearGradient></View>
  <View style={s.sectionHead}><View><Text style={s.section}>PURCHASES</Text><Text style={s.sectionSub}>Your WENIK activity</Text></View><Text style={s.sectionMeta}>{filtered.length} RECORDS</Text></View><TextInput style={s.search} placeholder="Search partner or amount" placeholderTextColor="#777783" value={q} onChangeText={setQ}/>
  {filtered.slice(0,purchaseVisible).map((x,i)=><View key={x.transaction_id||i} style={s.card}><View style={s.row}><Text style={s.cardTitle}>{x.partner_name||'WENIK Partner'}</Text><Text style={s.amount}>${Number(x.original_amount||0).toFixed(2)}</Text></View><Text style={s.meta}>{x.transaction_at?new Date(x.transaction_at).toLocaleString():''}</Text><View style={[s.row,{marginTop:8}]}><Text style={s.meta}>Final paid</Text><Text style={s.cardTitle}>${Number(x.final_amount||0).toFixed(2)}</Text></View></View>)}
  {purchaseVisible<filtered.length?<Pressable style={s.more} onPress={()=>setPurchaseVisible(v=>Math.min(v+20,filtered.length))}><Text style={s.moreText}>SHOW MORE PURCHASES</Text><Text style={s.moreMeta}>{purchaseVisible} OF {filtered.length}</Text></Pressable>:null}{!filtered.length?<View style={s.card}><Text style={s.meta}>No purchases found.</Text></View>:null}
  <View style={s.notificationHead}><View><Text style={s.section}>NOTIFICATIONS</Text><Text style={s.sectionSub}>WENIK news, offers & updates</Text></View><Text style={s.notificationCount}>{inbox.filter((x:any)=>!x.seen_at).length} UNREAD</Text></View>
  {inbox.slice(0,notificationVisible).map((x,i)=><Pressable accessibilityRole="button" accessibilityLabel={`${x.title||'WENIK notification'}${!x.seen_at?' new':''}`} key={x.message_id||i} onPress={()=>openMessage(x)} style={[s.card,!x.seen_at&&s.unread]}><View style={s.row}><Text style={s.cardTitle}>{x.title||'WENIK'}</Text>{!x.seen_at?<Text style={s.badge}>NEW</Text>:null}</View><Text style={s.body}>{x.body||''}</Text>{x.cta_url||x.deep_link||x.url?<Text style={s.openCta}>OPEN →</Text>:null}</Pressable>)}
  {notificationVisible<inbox.length?<Pressable style={s.more} onPress={()=>setNotificationVisible(v=>Math.min(v+20,inbox.length))}><Text style={s.moreText}>SHOW MORE NOTIFICATIONS</Text><Text style={s.moreMeta}>{notificationVisible} OF {inbox.length}</Text></Pressable>:null}{!inbox.length?<View style={s.card}><Text style={s.meta}>No notifications.</Text></View>:null}
  <Pressable style={s.logout} onPress={()=>supabase.auth.signOut()}><Text style={s.logoutText}>LOG OUT</Text></Pressable>
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7fb'},page:{padding:14,paddingTop:14,paddingBottom:110},hero:{padding:20,borderRadius:24,overflow:'hidden',borderWidth:1,borderColor:'rgba(178,92,255,.22)'},heroLine:{position:'absolute',top:0,left:0,right:0,height:3,backgroundColor:'#ef159d'},eye:{color:'#fff',fontSize:10,fontWeight:'900',letterSpacing:2},title:{color:'#fff',fontSize:30,fontWeight:'900'},sub:{color:'rgba(255,255,255,.9)',marginTop:4},profile:{backgroundColor:'#fff',borderRadius:24,padding:18,marginTop:14,borderWidth:1,borderColor:'rgba(178,92,255,.16)'},memberTop:{flexDirection:'row',alignItems:'center',gap:12},avatar:{width:48,height:48,borderRadius:16,backgroundColor:'#f4e8ff',alignItems:'center',justifyContent:'center'},avatarText:{color:'#8f24ff',fontSize:20,fontWeight:'900'},memberInfo:{flex:1},name:{color:'#18141d',fontSize:21,fontWeight:'900'},memberId:{color:'#99929f',fontSize:10,fontWeight:'800',marginTop:4,letterSpacing:.6},meta:{color:'#77717e',fontSize:12,marginTop:5},pointsCard:{borderRadius:18,padding:15,marginTop:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},pointsLabel:{color:'#ef159d',fontSize:9,fontWeight:'900',letterSpacing:1.1},points:{color:'#18141d',fontSize:27,fontWeight:'900',marginTop:2},pointsReady:{color:'#8f24ff',fontSize:8,fontWeight:'900',letterSpacing:.7},sectionHead:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between'},sectionMeta:{color:'#99929f',fontSize:9,fontWeight:'800',marginBottom:9},section:{color:'#ff6f21',fontSize:12,fontWeight:'900',letterSpacing:1.4,marginTop:25},sectionSub:{color:'#77717e',fontSize:10,marginTop:3,marginBottom:9},search:{height:50,borderRadius:16,paddingHorizontal:15,backgroundColor:'#fff',color:'#18141d',marginBottom:10},card:{backgroundColor:'#fff',borderRadius:19,padding:16,marginBottom:9,borderWidth:1,borderColor:'rgba(92,55,110,.07)'},unread:{borderColor:'#ef159d',backgroundColor:'#fff6fb'},notificationHead:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between'},notificationCount:{color:'#8f24ff',fontSize:9,fontWeight:'900',marginBottom:9},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},cardTitle:{color:'#18141d',fontWeight:'900',flexShrink:1},amount:{color:'#8f24ff',fontWeight:'900'},body:{color:'#77717e',marginTop:8,lineHeight:19},openCta:{color:'#8f24ff',fontSize:10,fontWeight:'900',marginTop:10},badge:{color:'#fff',backgroundColor:'#ef159d',fontSize:9,fontWeight:'900',paddingHorizontal:8,paddingVertical:4,borderRadius:12},more:{backgroundColor:'#fff',borderRadius:16,padding:13,alignItems:'center',marginBottom:10},moreText:{color:'#8f24ff',fontSize:10,fontWeight:'900'},moreMeta:{color:'#99929f',fontSize:9,fontWeight:'800',marginTop:3},logout:{marginTop:24,borderWidth:1,borderColor:'#ef159d',borderRadius:17,padding:15,alignItems:'center'},logoutText:{color:'#ef159d',fontWeight:'900'}});
