import { loadPartnerDirectory } from '../lib/partners';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Image, Linking, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { supabase } from '../lib/supabase';

type Partner={partner_id:string;business_name:string;area?:string;category?:string;address?:string;logo_url?:string;benefit_title?:string;benefit_type?:string;benefit_value?:number;benefit_conditions?:string;phone?:string;phone_number?:string;location_url?:string;google_maps_url?:string;menu_url?:string;instagram_url?:string;facebook_url?:string;website_url?:string};
type Ad={image_url?:string;title?:string;caption?:string};
const norm=(v:any)=>String(v??'').trim().toLowerCase();
function discount(x:Partner){const v=Number(x.benefit_value);if(Number.isFinite(v)&&v>0&&v<=100)return Math.round(v)+'% OFF';return x.benefit_title?'WENIK OFFER':''}

export default function Partners({initialPartnerId,onInitialPartnerOpened}:{initialPartnerId?:string|null,onInitialPartnerOpened?:()=>void}={}){
 const [rows,setRows]=useState<Partner[]>([]),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[cat,setCat]=useState('All'),[area,setArea]=useState('All'),[selected,setSelected]=useState<Partner|null>(null),[hero,setHero]=useState(''),[ads,setAds]=useState<Ad[]>([]),[visibleCount,setVisibleCount]=useState(24);
 useEffect(()=>{loadPartnerDirectory().then(({data})=>{const next=data||[];setRows(next);setLoading(false);if(initialPartnerId){const target=next.find((x:Partner)=>x.partner_id===initialPartnerId);if(target){open(target);onInitialPartnerOpened?.()}}})},[initialPartnerId]);
 const areas=useMemo(()=>['All',...Array.from(new Set(rows.map(x=>String(x.area||'').trim()).filter(Boolean))).sort((a,b)=>a.localeCompare(b))],[rows]);
 const categories=useMemo(()=>['All',...Array.from(new Set(rows.map(x=>String(x.category||'').trim()).filter(Boolean))).sort((a,b)=>a.localeCompare(b))],[rows]);
 const list=useMemo(()=>rows.filter(x=>{
   const hay=norm([x.business_name,x.area,x.category,x.address,x.benefit_title].join(' '));
   return (!q||hay.includes(norm(q)))&&(cat==='All'||norm(x.category)===norm(cat))&&(area==='All'||norm(x.area)===norm(area));
 }),[rows,q,cat,area]);
 useEffect(()=>{setVisibleCount(24)},[q,cat,area]);
 const visibleList=list.slice(0,visibleCount);
 async function open(x:Partner){setSelected(x);setHero(x.logo_url||'');setAds([]);const {data}=await supabase.rpc('public_partner_ads',{p_partner_id:x.partner_id});const next=(data||[]).filter((a:any)=>a?.image_url).slice(0,5);setAds(next);if(next[0]?.image_url)setHero(next[0].image_url)}
 return <SafeAreaView style={s.safe}><LinearGradient colors={['#b978f3','#f58bc5','#ffad86']} style={s.heroHead}><View style={s.heroLine}/><Text style={s.eye}>DISCOVER</Text><Text style={s.title}>WENIK Partners</Text><Text style={s.sub}>Discover benefits around you.</Text></LinearGradient>
  <TextInput style={s.search} placeholder="Search partners, area or category" placeholderTextColor="#777783" value={q} onChangeText={setQ}/>
  <View style={s.areaLabelRow}><Text style={s.filterLabel}>AREA</Text><Text style={s.resultCount}>{list.length} PARTNERS</Text></View><View style={s.chipBar}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{areas.map(x=><Pressable key={x} onPress={()=>setArea(x)} style={[s.chip,area===x&&s.areaChipOn]}><Text style={[s.chipText,area===x&&s.chipTextOn]}>{x}</Text></Pressable>)}</ScrollView></View><Text style={s.filterLabelStandalone}>CATEGORY</Text><View style={s.chipBar}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{categories.map(x=><Pressable key={x} onPress={()=>setCat(x)} style={[s.chip,cat===x&&s.chipOn]}><Text style={[s.chipText,cat===x&&s.chipTextOn]}>{x}</Text></Pressable>)}</ScrollView></View>
  {loading?<ActivityIndicator style={{marginTop:40}}/>:<ScrollView style={s.list} contentContainerStyle={s.grid}>{visibleList.map(x=><Pressable key={x.partner_id} style={s.card} onPress={()=>open(x)}>
    <View style={s.media}>{x.logo_url?<Image source={{uri:x.logo_url}} style={s.img}/>:<Text style={s.placeholder}>WENIK</Text>}{discount(x)?<Text style={s.off}>{discount(x)}</Text>:null}</View>
    <View style={s.body}><Text style={s.name} numberOfLines={2}>{x.business_name}</Text><Text style={s.meta} numberOfLines={1}>{[x.category,x.area].filter(Boolean).join(' · ')}</Text><Text style={s.promo} numberOfLines={2}>{x.benefit_title||'WENIK PARTNER'}</Text><Text style={s.viewPartner}>VIEW PARTNER →</Text></View>
  </Pressable>)}{visibleCount<list.length?<Pressable style={s.loadMore} onPress={()=>setVisibleCount(v=>Math.min(v+24,list.length))}><Text style={s.loadMoreText}>SHOW MORE PARTNERS</Text><Text style={s.loadMoreMeta}>{visibleCount} OF {list.length}</Text></Pressable>:null}{!list.length?<View style={s.empty}><Text style={s.meta}>No partners match your search.</Text></View>:null}</ScrollView>}
  <Modal visible={!!selected} transparent animationType="slide" onRequestClose={()=>setSelected(null)}><View style={s.modalBack}><View style={s.modal}>
    <Pressable onPress={()=>setSelected(null)}><Text style={s.close}>CLOSE ×</Text></Pressable>
    {hero?<Image source={{uri:hero}} style={s.hero}/>:<View style={[s.hero,s.heroFallback]}><Text style={s.placeholder}>WENIK</Text></View>}{ads.length>1?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.gallery}>{ads.map((a,i)=><Pressable key={i} onPress={()=>setHero(String(a.image_url))}><Image source={{uri:String(a.image_url)}} style={[s.thumb,hero===a.image_url&&s.thumbOn]}/></Pressable>)}</ScrollView>:null}
    <Text style={s.detailName}>{selected?.business_name}</Text><Text style={s.detailMeta}>{[selected?.category,selected?.area,selected?.address].filter(Boolean).join(' • ')}</Text>
    <View style={s.actions}>{(selected?.phone||selected?.phone_number)?<Pressable style={s.action} onPress={()=>Linking.openURL('tel:'+String(selected?.phone||selected?.phone_number).replace(/\s/g,''))}><Text style={s.actionText}>CALL</Text></Pressable>:null}{(selected?.location_url||selected?.google_maps_url)?<Pressable style={s.action} onPress={()=>Linking.openURL(String(selected?.location_url||selected?.google_maps_url))}><Text style={s.actionText}>LOCATION</Text></Pressable>:null}{selected?.menu_url?<Pressable style={s.action} onPress={()=>Linking.openURL(String(selected.menu_url))}><Text style={s.actionText}>MENU</Text></Pressable>:null}</View>
    {(selected?.instagram_url||selected?.facebook_url||selected?.website_url)?<View style={s.socials}>{selected?.instagram_url?<Pressable style={s.social} onPress={()=>Linking.openURL(String(selected.instagram_url))}><Text style={s.socialText}>INSTAGRAM</Text></Pressable>:null}{selected?.facebook_url?<Pressable style={s.social} onPress={()=>Linking.openURL(String(selected.facebook_url))}><Text style={s.socialText}>FACEBOOK</Text></Pressable>:null}{selected?.website_url?<Pressable style={s.social} onPress={()=>Linking.openURL(String(selected.website_url))}><Text style={s.socialText}>WEBSITE</Text></Pressable>:null}</View>:null}
    {selected?.benefit_title?<View style={s.offer}><Text style={s.offerStrong}>{discount(selected)}</Text><Text style={s.offerText}>{selected.benefit_title}</Text>{selected.benefit_conditions?<Text style={s.detailMeta}>{selected.benefit_conditions}</Text>:null}</View>:null}
  </View></View></Modal>
 </SafeAreaView>
}
const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:'#f8f7fb'},heroHead:{margin:14,marginBottom:4,padding:20,borderRadius:24,overflow:'hidden',borderWidth:1,borderColor:'rgba(178,92,255,.22)'},heroLine:{position:'absolute',top:0,left:0,right:0,height:3,backgroundColor:'#ef159d'},eye:{color:'#fff',fontSize:10,fontWeight:'900',letterSpacing:2},title:{color:'#fff',fontSize:28,fontWeight:'900'},sub:{color:'rgba(255,255,255,.9)',marginTop:3},
 search:{height:52,margin:16,marginBottom:8,borderRadius:17,paddingHorizontal:16,backgroundColor:'#fff',color:'#18141d',borderWidth:1,borderColor:'rgba(92,55,110,.12)'},
 areaLabelRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingHorizontal:16,marginTop:2},filterLabel:{color:'#8f24ff',fontSize:10,fontWeight:'900',letterSpacing:1.2},resultCount:{color:'#77717e',fontSize:9,fontWeight:'800'},filterLabelStandalone:{color:'#8f24ff',fontSize:10,fontWeight:'900',letterSpacing:1.2,paddingHorizontal:16,marginTop:2},chipBar:{height:50,marginBottom:4},chips:{paddingHorizontal:16,gap:8,paddingVertical:6,alignItems:'center'},chip:{height:38,paddingHorizontal:14,borderRadius:19,backgroundColor:'#fff',justifyContent:'center'},chipOn:{backgroundColor:'#ef159d'},areaChipOn:{backgroundColor:'#8f24ff'},chipText:{color:'#77717e',fontWeight:'800'},chipTextOn:{color:'#fff'},
 list:{flex:1},grid:{padding:16,paddingTop:8,paddingBottom:110,flexDirection:'row',flexWrap:'wrap',gap:12},card:{width:'48%',backgroundColor:'#fff',borderRadius:22,overflow:'hidden',borderWidth:1,borderColor:'rgba(178,92,255,.22)'},media:{aspectRatio:1,backgroundColor:'#f4ebff',alignItems:'center',justifyContent:'center'},img:{width:'100%',height:'100%',resizeMode:'cover'},placeholder:{fontSize:20,fontWeight:'900',color:'#8f24ff'},off:{position:'absolute',top:9,left:9,backgroundColor:'#ff5a00',color:'#fff',fontSize:11,fontWeight:'900',paddingHorizontal:9,paddingVertical:6,borderRadius:20},
 body:{minHeight:138,padding:12},name:{color:'#18141d',fontSize:16,fontWeight:'900',lineHeight:20,minHeight:40},meta:{color:'#77717e',fontSize:11,marginTop:4},promo:{color:'#ef159d',fontSize:10,fontWeight:'900',lineHeight:14,marginTop:7},viewPartner:{color:'#8f24ff',fontSize:9,fontWeight:'900',letterSpacing:.5,marginTop:10},
 loadMore:{width:'100%',backgroundColor:'#fff',borderRadius:18,padding:15,alignItems:'center',marginTop:2},loadMoreText:{color:'#8f24ff',fontSize:11,fontWeight:'900'},loadMoreMeta:{color:'#99929f',fontSize:9,fontWeight:'800',marginTop:4},empty:{width:'100%',backgroundColor:'#fff',borderRadius:18,padding:18,alignItems:'center'},modalBack:{flex:1,backgroundColor:'rgba(0,0,0,.72)',justifyContent:'flex-end'},modal:{backgroundColor:'#fff',borderTopLeftRadius:30,borderTopRightRadius:30,padding:20,paddingBottom:38,maxHeight:'90%'},close:{alignSelf:'flex-end',color:'#77717e',fontWeight:'900',marginBottom:12},hero:{width:'100%',aspectRatio:1.6,borderRadius:22,resizeMode:'cover'},gallery:{gap:8,paddingVertical:10},thumb:{width:72,height:58,borderRadius:12,opacity:.7},thumbOn:{opacity:1,borderWidth:2,borderColor:'#ef159d'},heroFallback:{backgroundColor:'#f4ebff',alignItems:'center',justifyContent:'center'},detailName:{color:'#18141d',fontSize:26,fontWeight:'900',marginTop:18},detailMeta:{color:'#77717e',fontSize:13,marginTop:6,lineHeight:19},offer:{backgroundColor:'#f8f2ff',padding:16,borderRadius:18,marginTop:16},offerStrong:{color:'#ff6f21',fontWeight:'900'},offerText:{color:'#18141d',fontSize:16,fontWeight:'800',marginTop:5},socials:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:10},social:{backgroundColor:'#f7f3fa',borderRadius:999,paddingVertical:9,paddingHorizontal:12,borderWidth:1,borderColor:'rgba(143,36,255,.10)'},socialText:{color:'#8f24ff',fontSize:8,fontWeight:'900',letterSpacing:.6},actions:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:14},action:{backgroundColor:'#8f24ff',borderRadius:14,paddingHorizontal:15,paddingVertical:11},actionText:{color:'#fff',fontSize:11,fontWeight:'900'}
});
