import { useEffect,useState } from 'react';
import { Pressable,SafeAreaView,StyleSheet,Text,View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import QRCode from 'react-native-qrcode-svg';
import { supabase } from '../lib/supabase';
export default function CustomerQr(){
 const [token,setToken]=useState(''),[expiry,setExpiry]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){setBusy(true);setError('');const {data,error:e}=await supabase.rpc('customer_refresh_qr');setBusy(false);if(e){setError(e.message);return}const r=Array.isArray(data)?data[0]:data;if(r){setToken(String(r.qr_token||''));setExpiry(r.qr_expires_at?new Date(r.qr_expires_at).toLocaleTimeString():'')}}
 useEffect(()=>{refresh()},[]);
 return <SafeAreaView style={s.safe}><View style={s.page}><LinearGradient colors={['#21103f','#110b1f','#221018']} style={s.hero}><View style={s.heroLine}/><Text style={s.eye}>YOUR ACCESS</Text><Text style={s.title}>My QR</Text><Text style={s.sub}>Show this code to a WENIK partner.</Text></LinearGradient><View style={s.box}>{token?<QRCode value={token} size={260} backgroundColor="white" color="black"/>:<Text style={s.loading}>{busy?"Loading…":"QR unavailable"}</Text>}</View>{error?<Text style={s.error}>{error}</Text>:null}{expiry?<Text style={s.exp}>Valid until {expiry}</Text>:null}<Pressable disabled={busy} style={[s.btn,busy&&{opacity:.55}]} onPress={refresh}><Text style={s.btnText}>{busy?"REFRESHING…":"REFRESH QR"}</Text></Pressable></View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#06050d'},page:{flex:1,padding:14,alignItems:'center'},hero:{width:'100%',padding:22,borderRadius:26,overflow:'hidden',borderWidth:1,borderColor:'rgba(255,255,255,.08)',marginBottom:28},heroLine:{position:'absolute',top:0,left:0,right:0,height:3,backgroundColor:'#ef159d'},eye:{color:'#c69cff',fontSize:11,fontWeight:'900',letterSpacing:2},title:{color:'#fff',fontSize:30,fontWeight:'900'},sub:{color:'#b9b4c8',marginTop:4,marginBottom:32},box:{backgroundColor:'#fff',padding:20,borderRadius:28,minWidth:300,minHeight:300,alignItems:'center',justifyContent:'center'},exp:{color:'#b9b4c8',marginTop:16},btn:{backgroundColor:'#ef159d',borderRadius:17,paddingHorizontal:28,paddingVertical:15,marginTop:18},btnText:{color:'#fff',fontWeight:'900'},loading:{color:'#777783',fontWeight:'800'},error:{color:'#ff6f21',textAlign:'center',marginTop:12,maxWidth:300}});
