import { useEffect,useRef,useState } from 'react';
import { AppState,ScrollView,Pressable,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import QRCode from 'react-native-qrcode-svg';
import { supabase } from '../lib/supabase';
export default function CustomerQr(){
 const [token,setToken]=useState(''),[expiry,setExpiry]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[lastUpdated,setLastUpdated]=useState('');
 const [expiresAt,setExpiresAt]=useState(0);const requestInFlight=useRef(false);
 async function refresh(){
  if(requestInFlight.current)return;requestInFlight.current=true;setBusy(true);setError('');setToken('');setExpiry('');
  try{const {data,error:e}=await supabase.rpc('customer_refresh_qr');if(e)throw e;const r=Array.isArray(data)?data[0]:data;
   const until=new Date(r?.qr_expires_at||'').getTime();
   if(!r?.qr_token||!Number.isFinite(until)||until<=Date.now())throw new Error('QR unavailable. Please refresh.');
   setToken(String(r.qr_token));setExpiresAt(until);setExpiry(new Date(until).toLocaleTimeString());setLastUpdated(new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}));
  }catch(e){setError(e instanceof Error?e.message:'Could not load QR. Please try again.');setExpiresAt(0);}
  finally{requestInFlight.current=false;setBusy(false);}
 }
 useEffect(()=>{refresh();const t=setInterval(()=>{if(AppState.currentState==='active')refresh()},4*60*1000);const sub=AppState.addEventListener('change',state=>{if(state==='active')refresh()});return()=>{clearInterval(t);sub.remove()}},[]);
 useEffect(()=>{if(!expiresAt)return;const t=setTimeout(()=>{setToken('');setExpiry('');setError('QR expired. Tap REFRESH QR.');},Math.max(0,expiresAt-Date.now()));return()=>clearTimeout(t)},[expiresAt]);

 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><LinearGradient colors={['#b978f3','#f58bc5','#ffad86']} style={s.hero}><View style={s.heroLine}/><Text style={s.eye}>YOUR ACCESS</Text><Text style={s.title}>My QR</Text><Text style={s.sub}>Show this code to a WENIK partner.</Text></LinearGradient><View style={s.accessLabel}><View style={s.liveDot}/><Text style={s.accessLabelText}>LIVE WENIK ACCESS</Text><Text style={s.secure}>SECURE</Text></View><View style={s.qrShell}><LinearGradient colors={['#8f24ff','#ef159d','#ff6f21']} style={s.qrAccent}/><View style={s.box}>{token?<QRCode value={token} size={260} backgroundColor="white" color="black"/>:<Text style={s.loading}>{busy?"Loading…":"QR unavailable"}</Text>}</View></View>{error?<Text style={s.error}>{error}</Text>:null}{expiry?<><View style={s.statusCard}><View><Text style={s.statusLabel}>QR STATUS</Text><Text style={s.exp}>Valid until {expiry}</Text></View>{lastUpdated?<View style={s.updatedBox}><Text style={s.updatedLabel}>UPDATED</Text><Text style={s.updated}>{lastUpdated}</Text></View>:null}</View><Text style={s.hint}>QR refreshes automatically for your security. Show only this live code to a WENIK partner.</Text></>:null}<Pressable disabled={busy} style={[s.btn,busy&&{opacity:.55}]} onPress={refresh}><Text style={s.btnText}>{busy?"REFRESHING…":"REFRESH QR"}</Text></Pressable></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7fb'},page:{flexGrow:1,padding:14,paddingBottom:28,alignItems:'center'},hero:{width:'100%',padding:22,borderRadius:26,overflow:'hidden',borderWidth:1,borderColor:'rgba(255,255,255,.08)',marginBottom:28},heroLine:{position:'absolute',top:0,left:0,right:0,height:3,backgroundColor:'#8f24ff'},eye:{color:'#fff',fontSize:11,fontWeight:'900',letterSpacing:2},title:{color:'#fff',fontSize:30,fontWeight:'900'},sub:{color:'rgba(255,255,255,.9)',marginTop:4},accessLabel:{flexDirection:'row',alignItems:'center',gap:7,marginBottom:10},liveDot:{width:8,height:8,borderRadius:4,backgroundColor:'#45c77b'},accessLabelText:{color:'#77717e',fontSize:9,fontWeight:'900',letterSpacing:1.4},secure:{color:'#8f24ff',fontSize:8,fontWeight:'900',letterSpacing:1,marginLeft:6},qrShell:{backgroundColor:'#fff',borderRadius:30,padding:3,overflow:'hidden',shadowColor:'#000',shadowOpacity:.07,shadowRadius:18,shadowOffset:{width:0,height:7},elevation:3},qrAccent:{position:'absolute',left:0,right:0,top:0,height:5},box:{backgroundColor:'#fff',padding:20,borderRadius:27,minWidth:300,minHeight:300,alignItems:'center',justifyContent:'center'},statusCard:{width:'100%',maxWidth:300,backgroundColor:'#fff',borderRadius:17,padding:13,flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:14,borderWidth:1,borderColor:'rgba(92,55,110,.08)'},statusLabel:{color:'#8f24ff',fontSize:8,fontWeight:'900',letterSpacing:1},exp:{color:'#77717e',fontSize:11,fontWeight:'700',marginTop:3},updatedBox:{alignItems:'flex-end'},updatedLabel:{color:'#99929f',fontSize:7,fontWeight:'900',letterSpacing:.8},updated:{color:'#18141d',fontSize:11,fontWeight:'900',marginTop:2},hint:{color:'#99929f',fontSize:10,lineHeight:15,marginTop:8,textAlign:'center',maxWidth:300},btn:{backgroundColor:'#8f24ff',borderRadius:17,borderWidth:1,borderColor:'rgba(255,255,255,.08)',paddingHorizontal:28,paddingVertical:15,marginTop:18},btnText:{color:'#fff',fontWeight:'900'},loading:{color:'#777783',fontWeight:'800'},error:{color:'#ff6f21',textAlign:'center',marginTop:12,maxWidth:300}});
