import { useEffect, useState } from 'react';
import { Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { supabase } from '../lib/supabase';
export default function Wins(){
 const [mine,setMine]=useState<any[]>([]),[recent,setRecent]=useState<any[]>([]),[gifts,setGifts]=useState<any[]>([]),[giftVisible,setGiftVisible]=useState(12),[giftQ,setGiftQ]=useState('');
 useEffect(()=>{Promise.all([supabase.rpc('customer_my_wins'),supabase.rpc('public_recent_winners',{p_limit:20}),supabase.rpc('public_active_win_gifts',{p_limit:500})]).then(([a,b,g])=>{setMine(a.data||[]);setRecent(b.data||[]);setGifts(g.data||[])})},[]);
 const filteredGifts=gifts.filter((g:any)=>String([g.gift_title,g.prize_name,g.title,g.partner_name].filter(Boolean).join(' ')).toLowerCase().includes(giftQ.trim().toLowerCase()));
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><LinearGradient colors={['#b978f3','#f58bc5','#ffad86']} style={s.hero}><Text style={s.heroEye}>WENIK WIN</Text><Text style={s.heroTitle}>Your chances. Your wins.</Text><Text style={s.heroSub}>Discover prizes, follow draws and celebrate WENIK winners.</Text></LinearGradient>
 <View style={s.sectionHead}><View><Text style={s.section}>ALL GIFTS</Text><Text style={s.gallerySub}>Gifts you can WIN</Text></View><Text style={s.count}>{filteredGifts.length} GIFTS</Text></View><TextInput value={giftQ} onChangeText={x=>{setGiftQ(x);setGiftVisible(12)}} placeholder="Search gifts or partners" placeholderTextColor="#99929f" style={s.giftSearch}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.giftRow}>{filteredGifts.slice(0,giftVisible).map((g,i)=><View key={g.prize_id||g.id||i} style={s.giftCard}><View style={s.winTag}><Text style={s.winTagText}>WIN</Text></View>{g.gift_image_url||g.image_url?<Image source={{uri:g.gift_image_url||g.image_url}} style={s.giftImage}/>:<View style={[s.giftImage,s.giftPlaceholder]}><Text style={s.giftPlaceholderText}>WENIK</Text></View>}<Text numberOfLines={2} style={s.giftTitle}>{g.gift_title||g.prize_name||g.title||'WENIK Gift'}</Text><Text numberOfLines={1} style={s.giftPartner}>{g.partner_name||'WENIK'}</Text></View>)}</ScrollView>{giftVisible<filteredGifts.length?<Pressable onPress={()=>setGiftVisible(v=>Math.min(v+12,filteredGifts.length))} style={s.moreBtn}><Text style={s.moreText}>SHOW MORE GIFTS</Text><Text style={s.moreMeta}>{giftVisible} OF {filteredGifts.length}</Text></Pressable>:null}{!filteredGifts.length?<View style={s.card}><Text style={s.muted}>{gifts.length?'No gifts match your search.':'New gifts are coming.'}</Text></View>:null}<View style={s.sectionHead}><Text style={s.section}>MY WINS</Text><Text style={s.count}>{mine.length}</Text></View>{mine.length?mine.map((x,i)=><View key={x.id||i} style={s.card}><Text style={s.eye}>YOUR WIN</Text><Text style={s.win}>🎉 {x.prize_name||'Prize'}</Text><Text style={s.muted}>Congratulations! You won with WENIK.</Text></View>):<View style={s.card}><Text style={s.muted}>No wins yet.</Text></View>}
 <View style={s.sectionHead}><Text style={s.section}>RECENT WINNERS</Text><Text style={s.count}>{recent.length}</Text></View>{recent.length?recent.map((x,i)=><View key={x.id||i} style={s.card}><View style={s.row}><Text style={s.name}>{x.public_display_name||'Winner'}</Text><Text style={s.badge}>WINNER</Text></View></View>):<View style={s.card}><Text style={s.muted}>No announced winners.</Text></View>}
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7fb'},page:{padding:14,paddingBottom:110},hero:{padding:22,borderRadius:26,marginBottom:6,minHeight:185,justifyContent:'center'},heroEye:{color:'#fff',fontSize:10,fontWeight:'900',letterSpacing:2},heroTitle:{color:'#fff',fontSize:29,fontWeight:'900',marginTop:5},heroSub:{color:'rgba(255,255,255,.92)',fontSize:12,lineHeight:18,marginTop:8,maxWidth:'90%'},heroPill:{alignSelf:'flex-start',backgroundColor:'rgba(255,255,255,.22)',paddingHorizontal:12,paddingVertical:7,borderRadius:999,marginTop:14},heroPillText:{color:'#fff',fontSize:8,fontWeight:'900',letterSpacing:1.2},heroSub:{color:'rgba(255,255,255,.9)',fontSize:12,lineHeight:17,marginTop:7,maxWidth:300},sectionHead:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',marginTop:24,marginBottom:9},section:{color:'#8f24ff',fontSize:12,fontWeight:'900',letterSpacing:1.4},count:{color:'#99929f',fontSize:9,fontWeight:'900',letterSpacing:.7},card:{backgroundColor:'#fff',padding:17,borderRadius:20,marginBottom:10},eye:{color:'#ef159d',fontSize:10,fontWeight:'900'},win:{color:'#18141d',fontSize:19,fontWeight:'900',marginTop:5},muted:{color:'#77717e',marginTop:5},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},name:{color:'#18141d',fontWeight:'900'},moreBtn:{alignSelf:'center',backgroundColor:'#fff',borderRadius:16,paddingHorizontal:18,paddingVertical:11,marginTop:12,borderWidth:1,borderColor:'rgba(92,55,110,.10)'},moreText:{color:'#8f24ff',fontSize:10,fontWeight:'900'},moreMeta:{color:'#99929f',fontSize:9,fontWeight:'800',marginTop:4},badge:{color:'#ff6f21',fontSize:10,fontWeight:'900'},giftSearch:{height:48,borderRadius:16,backgroundColor:'#fff',paddingHorizontal:15,color:'#18141d',marginBottom:12,borderWidth:1,borderColor:'rgba(92,55,110,.10)'},gallerySub:{color:'#77717e',fontSize:11,marginTop:3},giftRow:{gap:10,paddingRight:10},giftCard:{width:170,backgroundColor:'#fff',borderRadius:20,overflow:'hidden',paddingBottom:12,borderWidth:1,borderColor:'rgba(92,55,110,.08)'},giftImage:{width:'100%',height:125,resizeMode:'cover'},winTag:{position:'absolute',zIndex:2,top:9,left:9,backgroundColor:'#ef159d',borderRadius:999,paddingHorizontal:9,paddingVertical:5},winTagText:{color:'#fff',fontSize:8,fontWeight:'900',letterSpacing:.8},giftPlaceholder:{backgroundColor:'#f4ebff',alignItems:'center',justifyContent:'center'},giftPlaceholderText:{color:'#8f24ff',fontWeight:'900'},giftTitle:{color:'#18141d',fontWeight:'900',fontSize:15,marginTop:10,paddingHorizontal:12},giftPartner:{color:'#77717e',fontSize:11,marginTop:4,paddingHorizontal:12}});
