import { useEffect, useState } from 'react';
import { Image, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { supabase } from '../lib/supabase';
export default function Wins(){
 const [mine,setMine]=useState<any[]>([]),[recent,setRecent]=useState<any[]>([]),[gifts,setGifts]=useState<any[]>([]);
 useEffect(()=>{Promise.all([supabase.rpc('customer_my_wins'),supabase.rpc('public_recent_winners',{p_limit:20}),supabase.rpc('public_active_win_gifts',{p_limit:500})]).then(([a,b,g])=>{setMine(a.data||[]);setRecent(b.data||[]);setGifts(g.data||[])})},[]);
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><LinearGradient colors={['#b978f3','#f58bc5','#ffad86']} style={s.hero}><Text style={s.heroEye}>WENIK WIN</Text><Text style={s.heroTitle}>Your chances. Your wins.</Text></LinearGradient>
 <Text style={s.section}>ALL GIFTS</Text><Text style={s.gallerySub}>Gifts you can WIN</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.giftRow}>{gifts.map((g,i)=><View key={g.prize_id||g.id||i} style={s.giftCard}>{g.gift_image_url||g.image_url?<Image source={{uri:g.gift_image_url||g.image_url}} style={s.giftImage}/>:<View style={[s.giftImage,s.giftPlaceholder]}><Text style={s.giftPlaceholderText}>WENIK</Text></View>}<Text numberOfLines={2} style={s.giftTitle}>{g.gift_title||g.prize_name||g.title||'WENIK Gift'}</Text><Text numberOfLines={1} style={s.giftPartner}>{g.partner_name||'WENIK'}</Text></View>)}</ScrollView>{!gifts.length?<View style={s.card}><Text style={s.muted}>New gifts are coming.</Text></View>:null}<Text style={s.section}>MY WINS</Text>{mine.length?mine.map((x,i)=><View key={x.id||i} style={s.card}><Text style={s.eye}>YOUR WIN</Text><Text style={s.win}>🎉 {x.prize_name||'Prize'}</Text><Text style={s.muted}>Congratulations! You won with WENIK.</Text></View>):<View style={s.card}><Text style={s.muted}>No wins yet.</Text></View>}
 <Text style={s.section}>RECENT WINNERS</Text>{recent.length?recent.map((x,i)=><View key={x.id||i} style={s.card}><View style={s.row}><Text style={s.name}>{x.public_display_name||'Winner'}</Text><Text style={s.badge}>WINNER</Text></View></View>):<View style={s.card}><Text style={s.muted}>No announced winners.</Text></View>}
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7fb'},page:{padding:14,paddingBottom:110},hero:{padding:20,borderRadius:24,marginBottom:6},heroEye:{color:'#fff',fontSize:10,fontWeight:'900',letterSpacing:2},heroTitle:{color:'#fff',fontSize:27,fontWeight:'900',marginTop:5},section:{color:'#8f24ff',fontSize:12,fontWeight:'900',letterSpacing:1.4,marginTop:24,marginBottom:9},card:{backgroundColor:'#fff',padding:17,borderRadius:20,marginBottom:10},eye:{color:'#ef159d',fontSize:10,fontWeight:'900'},win:{color:'#18141d',fontSize:19,fontWeight:'900',marginTop:5},muted:{color:'#77717e',marginTop:5},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},name:{color:'#18141d',fontWeight:'900'},badge:{color:'#ff6f21',fontSize:10,fontWeight:'900'},gallerySub:{color:'#77717e',fontSize:13,marginTop:-5,marginBottom:10},giftRow:{gap:10,paddingRight:10},giftCard:{width:170,backgroundColor:'#fff',borderRadius:20,overflow:'hidden',paddingBottom:12},giftImage:{width:'100%',height:125},giftPlaceholder:{backgroundColor:'#f4ebff',alignItems:'center',justifyContent:'center'},giftPlaceholderText:{color:'#8f24ff',fontWeight:'900'},giftTitle:{color:'#18141d',fontWeight:'900',fontSize:15,marginTop:10,paddingHorizontal:12},giftPartner:{color:'#77717e',fontSize:11,marginTop:4,paddingHorizontal:12}});
