from pathlib import Path
p=Path('admin.html')
s=p.read_text()
old='<section id="subscriptions" class="panel">\n  <div class="card"><div class="row"><div><h2>Partner Subscriptions</h2><div class="muted">3 months FREE, then Manual or Whish payment.</div></div><button id="refreshSubscriptions" class="btn secondary" style="width:auto">REFRESH</button></div></div>\n  <div id="subscriptionList"></div>\n</section>'
new='<section id="subscriptions" class="panel">\n  <div class="card"><div class="row"><div><h2>Partner Subscriptions</h2><div class="muted">3 months FREE, then Manual or Whish payment.</div></div><button id="refreshSubscriptions" class="btn secondary" style="width:auto">REFRESH</button></div></div>\n  <div id="subscriptionAlerts"></div>\n  <!-- WENIK SUBSCRIPTION DUE ALERTS -->\n  <div id="subscriptionList"></div>\n</section>'
if old not in s: raise SystemExit('subscriptions section anchor not found')
s=s.replace(old,new,1)
old2="async function loadSubscriptions(){try{const list=await rpc('admin_partner_subscriptions');$('subscriptionList').innerHTML=(list||[]).map(s=>{const access=s.access_until?new Date(s.access_until).toLocaleDateString():'—';return '<div class=\"card\"><div class=\"row\"><div><b>'+esc(s.business_name)+'</b><div class=\"muted\">Access until '+esc(access)+(s.paid_until?' · Paid':' · 3 months FREE')+'</div></div><span class=\"pill\">'+esc(String(s.subscription_status||'').toUpperCase())+'</span></div><div class=\"two\"><input id=\"payAmount-'+s.partner_id+'\" class=\"field\" type=\"number\" min=\"0.01\" step=\"0.01\" placeholder=\"Amount\"><select id=\"payMethod-'+s.partner_id+'\" class=\"field\"><option value=\"manual\">Manual</option><option value=\"whish\">Whish</option></select></div><div class=\"two\"><input id=\"payMonths-'+s.partner_id+'\" class=\"field\" type=\"number\" min=\"1\" max=\"36\" value=\"1\" placeholder=\"Months\"><input id=\"payRef-'+s.partner_id+'\" class=\"field\" placeholder=\"Payment reference (optional)\"></div><button class=\"btn\" onclick=\"confirmPartnerPayment(\\\''+s.partner_id+'\\\',\\\''+String(s.business_name||'').replace(/'/g,'')+'\\\')\">CONFIRM PAYMENT</button></div>'}).join('')||'<div class=\"card muted\">No partner subscriptions.</div>'}catch(e){$('subscriptionList').innerHTML='<div class=\"card error\">'+esc(e.message)+'</div>'}}"
new2="async function loadSubscriptions(){try{const[list,alerts]=await Promise.all([rpc('admin_partner_subscriptions'),rpc('admin_partner_subscription_alerts')]);const amap=new Map((alerts||[]).map(a=>[a.partner_id,a]));const due=(alerts||[]).filter(a=>a.alert_level!=='ok');$('subscriptionAlerts').innerHTML=due.length?'<div class=\"card\"><div class=\"row\"><div><h3>⚠ Subscription Alerts</h3><div class=\"muted\">'+due.length+' partner(s) need attention.</div></div><span class=\"pill\">'+due.length+' ALERTS</span></div></div>':'<div class=\"card good\">✓ No subscription payments due soon.</div>';$('subscriptionList').innerHTML=(list||[]).map(s=>{const a=amap.get(s.partner_id)||{},access=s.access_until?new Date(s.access_until).toLocaleDateString():'—';let alarm='';if(a.alert_level==='expired')alarm='<div class=\"status error\">PAYMENT OVERDUE · ACCESS EXPIRED</div>';else if(a.alert_level==='urgent')alarm='<div class=\"status error\">PAYMENT DUE IN '+Math.max(0,Number(a.days_remaining||0))+' DAY(S)</div>';else if(a.alert_level==='due_soon')alarm='<div class=\"status\">PAYMENT DUE SOON · '+Number(a.days_remaining||0)+' DAY(S)</div>';else if(a.alert_level==='suspended')alarm='<div class=\"status error\">ACCOUNT SUSPENDED</div>';const safeName=String(s.business_name||'').replace(/'/g,'');const suspended=String(s.subscription_status||'')==='suspended';return '<div class=\"card\"><div class=\"row\"><div><b>'+esc(s.business_name)+'</b><div class=\"muted\">Access until '+esc(access)+(s.paid_until?' · Paid':' · 3 months FREE')+'</div>'+alarm+'</div><span class=\"pill\">'+esc(String(s.subscription_status||'').toUpperCase())+'</span></div><div class=\"two\"><input id=\"payAmount-'+s.partner_id+'\" class=\"field\" type=\"number\" min=\"0.01\" step=\"0.01\" placeholder=\"Amount\"><select id=\"payMethod-'+s.partner_id+'\" class=\"field\"><option value=\"manual\">Manual</option><option value=\"whish\">Whish</option></select></div><div class=\"two\"><input id=\"payMonths-'+s.partner_id+'\" class=\"field\" type=\"number\" min=\"1\" max=\"36\" value=\"1\" placeholder=\"Months\"><input id=\"payRef-'+s.partner_id+'\" class=\"field\" placeholder=\"Payment reference (optional)\"></div><div class=\"actions\"><button class=\"btn\" onclick=\"confirmPartnerPayment(\\\''+s.partner_id+'\\\',\\\''+safeName+'\\\')\">CONFIRM PAYMENT</button><button class=\"btn '+(suspended?'ok':'danger')+'\" onclick=\"setPartnerSuspended(\\\''+s.partner_id+'\\\','+(!suspended)+',\\\''+safeName+'\\\')\">'+(suspended?'REACTIVATE':'SUSPEND ACCOUNT')+'</button></div></div>'}).join('')||'<div class=\"card muted\">No partner subscriptions.</div>'}catch(e){$('subscriptionList').innerHTML='<div class=\"card error\">'+esc(e.message)+'</div>'}}"
if old2 not in s: raise SystemExit('loadSubscriptions anchor not found')
s=s.replace(old2,new2,1)
anchor="window.confirmPartnerPayment=async(id,name)=>{const amount=Number($('payAmount-'+id).value||0),months=Number($('payMonths-'+id).value||0),method=$('payMethod-'+id).value,ref=$('payRef-'+id).value.trim();if(!(amount>0)){alert('Enter payment amount.');return}if(!Number.isInteger(months)||months<1||months>36){alert('Enter valid subscription months.');return}if(!confirm('Confirm '+method.toUpperCase()+' payment for '+name+'?'))return;try{await rpc('admin_confirm_partner_payment',{p_partner_id:id,p_amount:amount,p_payment_method:method,p_period_months:months,p_provider_reference:ref||null,p_note:null});alert('Payment confirmed and subscription extended.');await loadSubscriptions()}catch(e){alert(e.message)}};"
add=anchor+"\nwindow.setPartnerSuspended=async(id,suspended,name)=>{const action=suspended?'SUSPEND':'REACTIVATE';if(!confirm(action+' '+name+'?'))return;try{await rpc('admin_set_partner_subscription_suspended',{p_partner_id:id,p_suspended:suspended,p_note:suspended?'Subscription payment overdue':null});alert(suspended?'Partner account suspended.':'Partner account reactivated.');await loadSubscriptions()}catch(e){alert(e.message)}};"
if anchor not in s: raise SystemExit('payment function anchor not found')
s=s.replace(anchor,add,1)
p.write_text(s)
print('subscription alerts UI patched')
