from pathlib import Path
p=Path('admin.html')
s=p.read_text()
old='<section id="super" class="panel"><div class="card"><div class="row"><div><h2>Super Admin</h2><div class="muted">Secure admin access control. Only Super Admin can change roles or disable access.</div></div><button id="refreshAdmins" class="btn secondary" style="width:auto">REFRESH</button></div><div id="superStatus" class="status"></div></div><div id="adminList"></div></section>'
new='<section id="super" class="panel"><div class="card"><div class="row"><div><h2>Super Admin</h2><div class="muted">Secure admin access control. Only Super Admin can create accounts, change roles or disable access.</div></div><button id="refreshAdmins" class="btn secondary" style="width:auto">REFRESH</button></div><div id="superStatus" class="status"></div></div><div class="card"><h2>Add Admin</h2><div class="muted">Create a secure WENIK management login.</div><input id="newAdminName" class="field" placeholder="Display name"><input id="newAdminEmail" class="field" type="email" placeholder="Admin email" autocomplete="off"><input id="newAdminPassword" class="field" type="password" minlength="8" placeholder="Temporary password · minimum 8 characters" autocomplete="new-password"><select id="newAdminRole" class="field"><option value="admin">Admin</option><option value="super_admin">Super Admin</option></select><button id="createAdminBtn" class="btn">ADD ADMIN</button><div id="createAdminStatus" class="status"></div></div><div id="adminList"></div></section>'
if old not in s: raise SystemExit('GUARD FAILED: exact Super Admin section not found')
s=s.replace(old,new,1)
needle="window.saveAdmin=async(id,name)=>{if(!confirm('Save this admin access change?'))return;try{const role=$('adminRole-'+id).value,active=$('adminActive-'+id).value==='true';await rpc('super_admin_update_admin',{p_admin_id:id,p_role:role,p_is_active:active,p_display_name:name||null});setStatus('superStatus','Admin access updated.',true);await loadAdmins()}catch(e){setStatus('superStatus',e.message)}};$('refreshAdmins').onclick=loadAdmins;"
addition=needle+"\n$('createAdminBtn').onclick=async()=>{try{if(profile?.role!=='super_admin')throw Error('Super Admin required.');const display_name=$('newAdminName').value.trim(),email=$('newAdminEmail').value.trim(),password=$('newAdminPassword').value,role=$('newAdminRole').value;if(!display_name||!email||!password)throw Error('Name, email and password are required.');if(password.length<8)throw Error('Password must be at least 8 characters.');$('createAdminBtn').disabled=true;setStatus('createAdminStatus','Creating secure admin account...',true);const{data,error}=await sb.functions.invoke('super-admin-create-admin',{body:{display_name,email,password,role}});if(error)throw error;if(data?.error)throw Error(data.error);$('newAdminName').value='';$('newAdminEmail').value='';$('newAdminPassword').value='';$('newAdminRole').value='admin';setStatus('createAdminStatus','Admin account created successfully.',true);await loadAdmins()}catch(e){setStatus('createAdminStatus',e.message||'Could not create admin.')}finally{$('createAdminBtn').disabled=false}};"
if needle not in s: raise SystemExit('GUARD FAILED: saveAdmin block not found')
s=s.replace(needle,addition,1)
if s.count('id="createAdminBtn"')!=1 or s.count("super-admin-create-admin")!=1: raise SystemExit('GUARD FAILED: create admin UI count')
p.write_text(s)
