from pathlib import Path
p=Path('admin.html'); s=p.read_text()
marker='<!-- WENIK ADMIN CREATE PARTNER UI -->'
if marker in s: raise SystemExit('already applied')
needle='<section id="subscriptions" class="panel">\n  <div class="card"><div class="row"><div><h2>Partner Subscriptions</h2>'
if needle not in s: raise SystemExit('subscriptions anchor missing')
replacement='''<section id="subscriptions" class="panel">\n  <!-- WENIK ADMIN CREATE PARTNER UI -->\n  <div class="card"><h2>Add Partner</h2><div class="muted">WENIK creates the Partner account. The Partner then logs in and completes business details, images and gifts. A 3-month FREE trial starts automatically.</div>\n    <input id="newPartnerBusiness" class="field" placeholder="Business name">\n    <div class="two"><input id="newPartnerCategory" class="field" placeholder="Category"><input id="newPartnerArea" class="field" placeholder="Area (optional)"></div>\n    <input id="newPartnerName" class="field" placeholder="Partner / manager display name">\n    <div class="two"><input id="newPartnerUsername" class="field" placeholder="Login username"><input id="newPartnerPassword" class="field" type="password" minlength="8" placeholder="Temporary password · minimum 8 characters"></div>\n    <button id="createPartnerBtn" class="btn">ADD PARTNER</button><div id="createPartnerStatus" class="status"></div>\n  </div>\n  <div class="card"><div class="row"><div><h2>Partner Subscriptions</h2>'''
s=s.replace(needle,replacement,1)
anchor="async function loadSubscriptions(){"
if anchor not in s: raise SystemExit('JS anchor missing')
js="""$('createPartnerBtn').onclick=async()=>{try{const business_name=$('newPartnerBusiness').value.trim(),category=$('newPartnerCategory').value.trim(),area=$('newPartnerArea').value.trim(),display_name=$('newPartnerName').value.trim(),username=$('newPartnerUsername').value.trim().toLowerCase(),password=$('newPartnerPassword').value;if(!business_name||!category||!username||!password)throw Error('Business, category, username and password are required.');if(password.length<8)throw Error('Password must be at least 8 characters.');$('createPartnerBtn').disabled=true;setStatus('createPartnerStatus','Creating Partner account...',true);const{data,error}=await sb.functions.invoke('admin-create-partner',{body:{business_name,category,area:area||null,display_name:display_name||business_name,username,password}});if(error)throw error;if(data?.error)throw Error(data.error);for(const id of ['newPartnerBusiness','newPartnerCategory','newPartnerArea','newPartnerName','newPartnerUsername','newPartnerPassword'])$(id).value='';setStatus('createPartnerStatus','Partner created · 3 months FREE until '+new Date(data.partner.trial_ends_at).toLocaleDateString()+'.',true);await loadSubscriptions()}catch(e){setStatus('createPartnerStatus',e.message||'Could not create Partner.')}finally{$('createPartnerBtn').disabled=false}};\n\n"""
s=s.replace(anchor,js+anchor,1)
p.write_text(s)
print('patched admin.html')
