from pathlib import Path

p=Path('index.html')
s=p.read_text()
old="""$('send').onclick=async()=>{\n  const f=$('first').value.trim(),l=$('last').value.trim();\n  if(!f||!l)return $('msg').textContent='First and last name are required.';\n  if(!$('terms').checked||!$('privacy').checked)return $('msg').textContent='Terms and Privacy are required.';\n  const p=ph($('phone').value);\n  const pw=$('newPassword').value;\n  if(pw.length<6)return $('msg').textContent='Password must be at least 6 characters.';\n  $('msg').textContent='Creating account…';\n  const{data,error}=await sb.auth.signUp({phone:p,password:pw,options:{data:{first_name:f,last_name:l,terms_accepted:true,privacy_accepted:true,marketing_consent:$('marketing').checked}}});\n  if(error)return $('msg').textContent=error.message;\n  if(!data.session)return $('msg').textContent='Phone confirmation is still enabled in Supabase.';\n  enter();\n};\n"""
new="""let otpPhone='';\nfunction showOtp(phone){\n  otpPhone=phone;\n  $('joinForm').classList.add('hidden');\n  $('loginForm').classList.add('hidden');\n  $('joinTab').classList.add('active');\n  $('loginTab').classList.remove('active');\n  $('authTitle').textContent='VERIFY PHONE';\n  let box=$('otpVerifyBox');\n  if(!box){\n    box=document.createElement('div');\n    box.id='otpVerifyBox';\n    box.innerHTML='<div class="muted" style="margin:8px 0 14px">We sent a 6-digit code to your mobile.</div><input id="otpCode" class="field" inputmode="numeric" autocomplete="one-time-code" maxlength="6" placeholder="6-digit code"><button id="verifyOtpBtn" class="btn" type="button">VERIFY CODE</button><button id="otpBackBtn" class="btn secondary" type="button">BACK</button><div id="otpMsg" class="muted" style="margin-top:10px"></div>';\n    $('joinForm').parentElement.appendChild(box);\n    $('verifyOtpBtn').onclick=verifyOtpCode;\n    $('otpBackBtn').onclick=()=>{box.classList.add('hidden');authMode('join')};\n    $('otpCode').addEventListener('input',e=>{e.target.value=e.target.value.replace(/\\D/g,'').slice(0,6)});\n    $('otpCode').addEventListener('keydown',e=>{if(e.key==='Enter')verifyOtpCode()});\n  }\n  box.classList.remove('hidden');\n  $('msg').textContent='';\n  $('otpMsg').textContent='Code sent. Enter it below.';\n  setTimeout(()=>$('otpCode')?.focus(),50);\n}\nasync function verifyOtpCode(){\n  const token=$('otpCode').value.replace(/\\D/g,'');\n  if(token.length!==6)return $('otpMsg').textContent='Enter the 6-digit code.';\n  $('otpMsg').textContent='Verifying…';\n  $('verifyOtpBtn').disabled=true;\n  const{data,error}=await sb.auth.verifyOtp({phone:otpPhone,token,type:'sms'});\n  $('verifyOtpBtn').disabled=false;\n  if(error)return $('otpMsg').textContent=error.message;\n  if(!data?.session)return $('otpMsg').textContent='Verification succeeded but no session was created. Please try Login.';\n  $('otpMsg').textContent='Verified ✓';\n  enter();\n}\n\n$('send').onclick=async()=>{\n  const f=$('first').value.trim(),l=$('last').value.trim();\n  if(!f||!l)return $('msg').textContent='First and last name are required.';\n  if(!$('terms').checked||!$('privacy').checked)return $('msg').textContent='Terms and Privacy are required.';\n  const p=ph($('phone').value);\n  const pw=$('newPassword').value;\n  if(pw.length<6)return $('msg').textContent='Password must be at least 6 characters.';\n  $('msg').textContent='Creating account…';\n  const{data,error}=await sb.auth.signUp({phone:p,password:pw,options:{data:{first_name:f,last_name:l,terms_accepted:true,privacy_accepted:true,marketing_consent:$('marketing').checked}}});\n  if(error)return $('msg').textContent=error.message;\n  if(!data.session)return showOtp(p);\n  enter();\n};\n"""
if old not in s:
    raise SystemExit('AUTH BLOCK NOT FOUND')
s=s.replace(old,new,1)
p.write_text(s)
print('OTP preview patch applied')
