from pathlib import Path
p=Path('admin.html')
s=p.read_text()
old="async function loadWins(){try{const list=await rpc('admin_campaign_list');$('winList').innerHTML=(list||[]).map(c=>{const remaining=Math.max(Number(c.prize_slots||0)-Number(c.winner_count||0),0);const canDraw=c.entries_locked_at&&remaining>0&&!c.draw_finalized_at&&c.status==='closed';return '<div class=\"card\"><div class=\"row\"><div><b>'+esc(c.title)+'</b><div class=\"muted\">'+esc(c.code)+'</div></div><span class=\"pill\">'+esc(c.status)+'</span></div><div class=\"muted\">Eligible '+c.eligible_entries+' · Prize slots '+c.prize_slots+' · Winners '+c.winner_count+' · Remaining '+remaining+'</div>'+(canDraw?'<div class=\"two\"><input id=\"drawCount-'+c.id+'\" class=\"field\" type=\"number\" min=\"1\" max=\"'+remaining+'\" value=\"'+Math.min(4,remaining)+'\" placeholder=\"Number of winners\"><button class=\"btn\" onclick=\"drawWin(\\''+c.id+'\\','+remaining+','+Number(c.eligible_entries||0)+')\">RUN DRAW</button></div>':'')+'</div>'}).join('')||'<div class=\"card muted\">No WIN campaigns.</div>'}catch(e){$('winList').innerHTML='<div class=\"card error\">'+esc(e.message)+'</div>'}}"
new="async function loadWins(){try{const [list,winners]=await Promise.all([rpc('admin_campaign_list'),rpc('admin_winner_list',{p_campaign_id:null})]);$('winList').innerHTML=(list||[]).map(c=>{const remaining=Math.max(Number(c.prize_slots||0)-Number(c.winner_count||0),0);const canDraw=c.entries_locked_at&&remaining>0&&!c.draw_finalized_at&&c.status==='closed';const cw=(winners||[]).filter(w=>w.campaign_id===c.id);const winnerHtml=cw.length?'<div class=\\\"muted\\\" style=\\\"margin-top:12px;font-weight:800\\\">WINNERS</div>'+cw.map(w=>'<div class=\\\"card\\\" style=\\\"margin-top:8px\\\"><div class=\\\"row\\\"><div><b>'+esc(w.customer_name)+'</b><div class=\\\"muted\\\">'+esc(w.prize_title)+' · '+esc(w.wenik_id||'')+'</div></div><span class=\\\"pill\\\">'+(w.announced_at?'published':'pending')+'</span></div>'+(w.announced_at?'<div class=\\\"muted\\\">Public: '+esc(w.public_display_name||'')+'</div>':'<button class=\\\"btn\\\" onclick=\\\"publishWinner(\\\''+w.winner_id+'\\\')\\\">PUBLISH WINNER</button>')+'</div>').join(''):'';return '<div class=\"card\"><div class=\"row\"><div><b>'+esc(c.title)+'</b><div class=\"muted\">'+esc(c.code)+'</div></div><span class=\"pill\">'+esc(c.status)+'</span></div><div class=\"muted\">Eligible '+c.eligible_entries+' · Prize slots '+c.prize_slots+' · Winners '+c.winner_count+' · Remaining '+remaining+'</div>'+(canDraw?'<div class=\"two\"><input id=\"drawCount-'+c.id+'\" class=\"field\" type=\"number\" min=\"1\" max=\"'+remaining+'\" value=\"'+Math.min(4,remaining)+'\" placeholder=\"Number of winners\"><button class=\"btn\" onclick=\"drawWin(\\''+c.id+'\\','+remaining+','+Number(c.eligible_entries||0)+')\">RUN DRAW</button></div>':'')+winnerHtml+'</div>'}).join('')||'<div class=\"card muted\">No WIN campaigns.</div>'}catch(e){$('winList').innerHTML='<div class=\"card error\">'+esc(e.message)+'</div>'}}\nwindow.publishWinner=async id=>{if(!confirm('Publish this winner and notify the customer?'))return;try{await rpc('admin_publish_winner',{p_winner_id:id,p_public_name:null});alert('Winner published and customer notified.');await loadWins()}catch(e){alert(e.message)}};"
if old not in s: raise SystemExit('GUARD FAILED: exact loadWins block not found')
s2=s.replace(old,new,1)
if s2.count('window.publishWinner=')!=1: raise SystemExit('GUARD FAILED: publishWinner count')
p.write_text(s2)
