from pathlib import Path
p=Path('index.html'); s=p.read_text()
marker='/* WENIK AUTH FINAL V5 */'
if marker in s: raise SystemExit('already patched')
css='''\n<style>\n/* WENIK AUTH FINAL V5 */\n.top{display:none!important}\n#auth{margin-top:0!important;padding-top:0!important}\n#auth .authBrandV4{display:none!important}\n#auth .authBrandFinal{position:relative;overflow:hidden;background:#fff;color:#111;text-align:center;margin:0 -1px 16px;padding:18px 10px 22px;border-radius:0 0 24px 24px;box-shadow:0 10px 30px rgba(50,20,70,.08)}\n#auth .authBrandFinal:before,#auth .authBrandFinal:after{content:"";position:absolute;bottom:-30px;width:60%;height:74px;background:linear-gradient(100deg,#7b20ef,#ef159d,#ff6f21,#ffd21c);z-index:0}#auth .authBrandFinal:before{left:-18%;transform:skewY(-10deg);border-radius:0 90% 0 0}#auth .authBrandFinal:after{right:-18%;transform:skewY(10deg);border-radius:90% 0 0 0}\n.authBrandFinal .bfMark{position:relative;z-index:2;font-size:64px;font-weight:1000;line-height:.8;background:linear-gradient(135deg,#8f24ff,#ef159d 48%,#ff6f21 76%,#ffd21c);-webkit-background-clip:text;background-clip:text;color:transparent}.authBrandFinal .bfName{position:relative;z-index:2;font-size:32px;font-weight:1000;line-height:1.05;margin-top:9px}.authBrandFinal .bfName span{background:linear-gradient(90deg,#8f24ff,#ef159d,#ff6f21,#ffd21c);-webkit-background-clip:text;background-clip:text;color:transparent}.authBrandFinal .bfWin{position:relative;z-index:2;font-size:10px;font-weight:1000;letter-spacing:5px;margin:4px 0 14px}.authBrandFinal .bfActions{position:relative;z-index:2;display:grid;grid-template-columns:repeat(4,1fr);gap:3px;max-width:520px;margin:0 auto 13px}.authBrandFinal .bfAction{border-right:1px solid #eee}.authBrandFinal .bfAction:last-child{border:0}.authBrandFinal .bfIcon{font-size:21px;line-height:1.1}.authBrandFinal .bfAction b{display:block;font-size:9px}.authBrandFinal .bfAction small{display:block;font-size:5.5px;color:#555;white-space:nowrap}.authBrandFinal .bfUrl{position:relative;z-index:2;display:inline-block;background:#fff;border:1.5px solid transparent;border-radius:999px;padding:6px 20px;font-size:9px;font-weight:1000;letter-spacing:1.5px;background:linear-gradient(#fff,#fff) padding-box,linear-gradient(90deg,#8f24ff,#ef159d,#ff6f21,#ffd21c) border-box}\n@media(max-width:430px){#auth .authBrandFinal{padding:15px 6px 19px}.authBrandFinal .bfMark{font-size:58px}.authBrandFinal .bfName{font-size:29px}.authBrandFinal .bfWin{font-size:9px;margin-bottom:11px}.authBrandFinal .bfIcon{font-size:19px}.authBrandFinal .bfAction b{font-size:8px}.authBrandFinal .bfAction small{font-size:5px}.authBrandFinal .bfUrl{font-size:8px;padding:5px 16px}}\n</style>\n'''
head=s.lower().rfind('</head>'); assert head>=0
s=s[:head]+css+s[head:]
needle='<section id="auth" class="hero">'; pos=s.find(needle); assert pos>=0
end=s.find('>',pos); assert end>=0
brand='''<div class="authBrandFinal" aria-label="WENIK.CO WIN-WIN"><div class="bfMark">W</div><div class="bfName"><span>WENIK</span>.CO</div><div class="bfWin">— WIN - WIN —</div><div class="bfActions"><div class="bfAction"><div class="bfIcon">🎁</div><b>REWARDS</b><small>MORE IS YOURS</small></div><div class="bfAction"><div class="bfIcon">🤝</div><b>PARTNERS</b><small>TOGETHER WE GROW</small></div><div class="bfAction"><div class="bfIcon">▣</div><b>SCAN</b><small>EARN &amp; WIN</small></div><div class="bfAction"><div class="bfIcon">📈</div><b>GROW</b><small>MORE TOGETHER</small></div></div><div class="bfUrl">◎ WWW.WENIK.CO</div></div>'''
s=s[:end+1]+brand+s[end+1:]
p.write_text(s)
