from pathlib import Path
p=Path('admin.html')
s=p.read_text(encoding='utf-8')
MARK='<!-- WENIK REPORTS FINAL V1 -->'
if MARK in s:
    print('Reports final already present'); raise SystemExit(0)

old='''<section id="reports" class="panel active"><div class="card"><div class="two"><select id="period" class="field"><option value="today">Today</option><option value="month">This month</option><option value="all">All time</option></select><button id="refreshReports" class="btn">REFRESH REPORTS</button></div></div><div id="summary" class="grid"></div><h2>Gift Inventory</h2>'''
new='''<section id="reports" class="panel active"><div class="card"><div class="two"><select id="period" class="field"><option value="today">Today</option><option value="month">This month</option><option value="all">All time</option></select><button id="refreshReports" class="btn">REFRESH REPORTS</button></div></div>
<!-- WENIK REPORTS FINAL V1 -->
<div class="card"><h3>Report Tools</h3><div class="two"><input id="partnerReportSearch" class="field" placeholder="Search partner"><select id="partnerReportSort" class="field"><option value="visits">Sort partners · Visits</option><option value="sales">Sort partners · Final sales</option><option value="bills">Sort partners · Bills</option><option value="customers">Sort partners · Customers</option><option value="name">Sort partners · Name</option></select></div><div class="two"><input id="customerReportSearch" class="field" placeholder="Search customer / WENIK ID"><select id="customerReportLimit" class="field"><option value="10">Top 10 customers</option><option value="25">Top 25 customers</option><option value="50" selected>Top 50 customers</option><option value="100">Top 100 customers</option></select></div><div class="actions"><button id="exportPartnerReports" class="btn secondary">EXPORT PARTNERS CSV</button><button id="exportCustomerReports" class="btn secondary">EXPORT CUSTOMERS CSV</button></div><div id="reportToolsStatus" class="status"></div></div>
<div id="summary" class="grid"></div><h2>Gift Inventory</h2>'''
assert old in s, 'reports html anchor missing'
s=s.replace(old,new,1)

old_func="""async function loadReports(){try{$('refreshReports').disabled=true;await loadGiftInventoryReport();const dates=range(),directory=await rpc('public_partner_directory_v2');const reports=await Promise.all((directory||[]).map(async p=>({p,r:(await rpc('admin_partner_report',{p_partner_id:p.partner_id,...dates}))?.[0]||{}})));const total=reports.reduce((a,x)=>{for(const k of ['total_transactions','unique_customers','original_bill_value','benefits_value','final_sales'])a[k]+=Number(x.r[k]||0);return a},{total_transactions:0,unique_customers:0,original_bill_value:0,benefits_value:0,final_sales:0});$('summary').innerHTML=[['Visits',total.total_transactions],['Customers',total.unique_customers],['Bills',money(total.original_bill_value)],['Benefits',money(total.benefits_value)],['Final sales',money(total.final_sales)]].map(x=>'<div class=\"metric\"><span class=\"muted\">'+x[0]+'</span><b>'+x[1]+'</b></div>').join('');$('partners').innerHTML=reports.map(x=>'<div class=\"card\"><div class=\"row\"><h3>'+esc(x.p.business_name)+'</h3><span class=\"pill\">'+Number(x.r.total_transactions||0)+' visits</span></div><div class=\"muted\">Customers '+Number(x.r.unique_customers||0)+' · Bills '+money(x.r.original_bill_value)+' · Benefits '+money(x.r.benefits_value)+' · Final '+money(x.r.final_sales)+'</div></div>').join('')||'<div class=\"card muted\">No partners.</div>';const top=await rpc('admin_top_customers',{...dates,p_limit:10});$('customers').innerHTML=(top||[]).map((x,i)=>'<div class=\"card\"><div class=\"row\"><b>'+(i+1)+'. '+esc(x.full_name)+'</b><b>'+money(x.total_spend)+'</b></div><div class=\"muted\">'+esc(x.wenik_id)+' · '+x.total_transactions+' visits · '+x.unique_partners+' partners</div></div>').join('')||'<div class=\"card muted\">No customer activity.</div>'}catch(e){$('partners').innerHTML='<div class=\"card error\">'+esc(e.message)+'</div>'}finally{$('refreshReports').disabled=false}}"""
assert old_func in s, 'loadReports anchor missing'
new_func=r'''let reportPartnerRows=[],reportCustomerRows=[];
function csvCell(v){const x=String(v??'').replace(/"/g,'""');return '"'+x+'"'}
function downloadCsv(filename,headers,rows){const csv='\ufeff'+[headers.map(csvCell).join(','),...rows.map(r=>r.map(csvCell).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=filename;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function renderPartnerReports(){let rows=[...reportPartnerRows],q=$('partnerReportSearch').value.trim().toLowerCase(),sort=$('partnerReportSort').value;if(q)rows=rows.filter(x=>String(x.p.business_name||'').toLowerCase().includes(q));const val=(x,k)=>Number(x.r[k]||0);rows.sort((a,b)=>sort==='name'?String(a.p.business_name||'').localeCompare(String(b.p.business_name||'')):sort==='sales'?val(b,'final_sales')-val(a,'final_sales'):sort==='bills'?val(b,'original_bill_value')-val(a,'original_bill_value'):sort==='customers'?val(b,'unique_customers')-val(a,'unique_customers'):val(b,'total_transactions')-val(a,'total_transactions'));$('partners').innerHTML=rows.map(x=>{const visits=val(x,'total_transactions'),avg=visits?val(x,'original_bill_value')/visits:0;return '<div class="card"><div class="row"><h3>'+esc(x.p.business_name)+'</h3><span class="pill">'+visits+' visits</span></div><div class="muted">Customers '+val(x,'unique_customers')+' · Bills '+money(val(x,'original_bill_value'))+' · Benefits '+money(val(x,'benefits_value'))+' · Final '+money(val(x,'final_sales'))+' · Avg bill '+money(avg)+'</div></div>'}).join('')||'<div class="card muted">No matching partners.</div>'}
function renderCustomerReports(){const q=$('customerReportSearch').value.trim().toLowerCase();const rows=reportCustomerRows.filter(x=>!q||String(x.full_name||'').toLowerCase().includes(q)||String(x.wenik_id||'').toLowerCase().includes(q));$('customers').innerHTML=rows.map((x,i)=>'<div class="card"><div class="row"><b>'+(i+1)+'. '+esc(x.full_name)+'</b><b>'+money(x.total_spend)+'</b></div><div class="muted">'+esc(x.wenik_id)+' · '+Number(x.total_transactions||0)+' visits · '+Number(x.unique_partners||0)+' partners</div></div>').join('')||'<div class="card muted">No matching customer activity.</div>'}
async function loadReports(){try{$('refreshReports').disabled=true;$('reportToolsStatus').textContent='Loading reports…';await loadGiftInventoryReport();const dates=range(),directory=await rpc('public_partner_directory_v2');reportPartnerRows=await Promise.all((directory||[]).map(async p=>({p,r:(await rpc('admin_partner_report',{p_partner_id:p.partner_id,...dates}))?.[0]||{}})));const total=reportPartnerRows.reduce((a,x)=>{for(const k of ['total_transactions','unique_customers','original_bill_value','benefits_value','final_sales'])a[k]+=Number(x.r[k]||0);return a},{total_transactions:0,unique_customers:0,original_bill_value:0,benefits_value:0,final_sales:0}),avgBill=total.total_transactions?total.original_bill_value/total.total_transactions:0,benefitRate=total.original_bill_value?total.benefits_value*100/total.original_bill_value:0;$('summary').innerHTML=[['Visits',total.total_transactions],['Customers',total.unique_customers],['Bills',money(total.original_bill_value)],['Benefits',money(total.benefits_value)],['Final sales',money(total.final_sales)],['Avg bill',money(avgBill)],['Benefit rate',benefitRate.toFixed(1)+'%']].map(x=>'<div class="metric"><span class="muted">'+x[0]+'</span><b>'+x[1]+'</b></div>').join('');renderPartnerReports();reportCustomerRows=await rpc('admin_top_customers',{...dates,p_limit:Number($('customerReportLimit').value||50)});renderCustomerReports();$('reportToolsStatus').textContent=''}catch(e){$('partners').innerHTML='<div class="card error">'+esc(e.message)+'</div>';$('reportToolsStatus').textContent=String(e.message||e)}finally{$('refreshReports').disabled=false}}
$('partnerReportSearch').oninput=renderPartnerReports;$('partnerReportSort').onchange=renderPartnerReports;$('customerReportSearch').oninput=renderCustomerReports;$('customerReportLimit').onchange=loadReports;
$('exportPartnerReports').onclick=()=>{const rows=reportPartnerRows.map(x=>[x.p.business_name,Number(x.r.total_transactions||0),Number(x.r.unique_customers||0),Number(x.r.original_bill_value||0).toFixed(2),Number(x.r.benefits_value||0).toFixed(2),Number(x.r.final_sales||0).toFixed(2)]);downloadCsv('wenik-partner-report.csv',['Partner','Visits','Unique Customers','Bills','Benefits','Final Sales'],rows);setStatus('reportToolsStatus','Partner report exported.',true)};
$('exportCustomerReports').onclick=()=>{const rows=reportCustomerRows.map(x=>[x.full_name,x.wenik_id,Number(x.total_transactions||0),Number(x.unique_partners||0),Number(x.total_spend||0).toFixed(2)]);downloadCsv('wenik-customer-report.csv',['Customer','WENIK ID','Visits','Unique Partners','Total Spend'],rows);setStatus('reportToolsStatus','Customer report exported.',true)};'''
s=s.replace(old_func,new_func,1)

p.write_text(s,encoding='utf-8')
print('Final Admin Reports UI applied')
