from pathlib import Path
p=Path('admin.html')
s=p.read_text()
old_section='<section id="super" class="panel"><div class="card"><h2>Super Admin</h2><div class="muted">Admin accounts and access overview.</div></div><div id="adminList"></div></section>'
new_section='<section id="super" class="panel"><div class="card"><div class="row"><div><h2>Super Admin</h2><div class="muted">Secure admin access control. Only Super Admin can change roles or disable access.</div></div><button id="refreshAdmins" class="btn secondary" style="width:auto">REFRESH</button></div><div id="superStatus" class="status"></div></div><div id="adminList"></div></section>'
if old_section not in s: raise SystemExit('GUARD FAILED: Super Admin section not found')
s=s.replace(old_section,new_section,1)
old="async function loadAdmins(){if(profile?.role!=='super_admin')return;try{const list=await rpc('super_admin_list_admins');$('adminList').innerHTML=(list||[]).map(a=>'<div class=\"card\"><div class=\"row\"><b>'+esc(a.display_name)+'</b><span class=\"pill\">'+esc(String(a.role).replace('_',' '))+'</span></div><div class=\"muted\">'+(a.is_active?'Active':'Disabled')+' · '+new Date(a.created_at).toLocaleString()+'</div></div>').join('')||'<div class=\"card muted\">No admin accounts.</div>'}catch(e){$('adminList').innerHTML='<div class=\"card error\">'+esc(e.message)+'</div>'}}"
new="async function loadAdmins(){if(profile?.role!=='super_admin')return;try{const list=await rpc('super_admin_list_admins');$('adminList').innerHTML=(list||[]).map(a=>{const self=a.id===profile.id;return '<div class=\"card\"><div class=\"row\"><div><b>'+esc(a.display_name||'WENIK Admin')+'</b><div class=\"muted\">'+(a.is_active?'Active':'Disabled')+' · '+new Date(a.created_at).toLocaleString()+(self?' · YOU':'')+'</div></div><span class=\"pill\">'+esc(String(a.role).replace('_',' '))+'</span></div><div class=\"two\"><select id=\"adminRole-'+a.id+'\" class=\"field\" '+(self?'disabled':'')+'><option value=\"admin\" '+(a.role==='admin'?'selected':'')+'>Admin</option><option value=\"super_admin\" '+(a.role==='super_admin'?'selected':'')+'>Super Admin</option></select><select id=\"adminActive-'+a.id+'\" class=\"field\" '+(self?'disabled':'')+'><option value=\"true\" '+(a.is_active?'selected':'')+'>Active</option><option value=\"false\" '+(!a.is_active?'selected':'')+'>Disabled</option></select></div>'+(self?'<div class=\"muted\" style=\"margin-top:10px\">Your Super Admin account is protected from self-disable or demotion.</div>':'<button class=\"btn\" onclick=\"saveAdmin(\\''+a.id+'\\',\\''+String(a.display_name||'').replace(/'/g,'')+'\\')\">SAVE ACCESS</button>')+'</div>'}).join('')||'<div class=\"card muted\">No admin accounts.</div>';setStatus('superStatus','Admin access loaded securely.',true)}catch(e){$('adminList').innerHTML='<div class=\"card error\">'+esc(e.message)+'</div>'}}\nwindow.saveAdmin=async(id,name)=>{if(!confirm('Save this admin access change?'))return;try{const role=$('adminRole-'+id).value,active=$('adminActive-'+id).value==='true';await rpc('super_admin_update_admin',{p_admin_id:id,p_role:role,p_is_active:active,p_display_name:name||null});setStatus('superStatus','Admin access updated.',true);await loadAdmins()}catch(e){setStatus('superStatus',e.message)}};$('refreshAdmins').onclick=loadAdmins;"
if old not in s: raise SystemExit('GUARD FAILED: loadAdmins block not found')
s=s.replace(old,new,1)
if s.count('super_admin_update_admin')!=1: raise SystemExit('GUARD FAILED: update RPC wiring count')
p.write_text(s)
