from pathlib import Path

p=Path('admin.html')
s=p.read_text(encoding='utf-8')
MARK='WENIK ADMIN DASHBOARD MOBILE POLISH V1'
if MARK in s:
    raise SystemExit('already applied')

old='''<section id="dashboard" class="panel">\n  <div class="card">\n    <div class="row"><div><h2>Home Dashboard</h2><div class="muted">Control customer home banners without touching the website code.</div></div><button id="refreshHomeAds" class="btn secondary" style="width:auto">REFRESH</button></div>\n  </div>\n  <div class="card">\n    <h3>Add / Edit Banner</h3>\n    <input id="homeAdId" type="hidden">\n    <input id="homeAdImage" class="field" placeholder="Image URL · required">\n    <input id="homeAdTitle" class="field" placeholder="Title (optional)">\n    <div class="two"><select id="homeAdCtaType" class="field"><option value="partner_page">Partner page</option><option value="url">URL</option><option value="none">No action</option></select><input id="homeAdCtaUrl" class="field" placeholder="CTA URL or /path"></div>\n    <div class="two"><input id="homeAdSort" class="field" type="number" value="100" placeholder="Sort order"><input id="homeAdPriority" class="field" type="number" value="0" placeholder="Priority"></div>\n    <div class="two"><input id="homeAdStart" class="field" type="datetime-local"><input id="homeAdEnd" class="field" type="datetime-local"></div>\n    <select id="homeAdActive" class="field"><option value="false">Inactive</option><option value="true">Active</option></select>\n    <div class="actions"><button id="saveHomeAd" class="btn">SAVE BANNER</button><button id="clearHomeAd" class="btn secondary">CLEAR</button></div>\n    <div id="homeAdStatus" class="status"></div>\n  </div>\n  <div id="homeAdsList"></div>\n</section>'''

new='''<section id="dashboard" class="panel">\n  <!-- WENIK ADMIN DASHBOARD MOBILE POLISH V1 -->\n  <div class="card wenikDashHead">\n    <div class="row"><div><div class="sub">CUSTOMER HOME</div><h2>Home Dashboard</h2><div class="muted">Manage the rotating customer banners from here.</div></div><button id="refreshHomeAds" class="btn secondary wenikMiniBtn">REFRESH</button></div>\n  </div>\n  <div class="card wenikDashEditor">\n    <div class="row"><div><div class="sub">BANNER EDITOR</div><h3>Add / Edit Banner</h3></div><span class="pill">AUTO SIZE</span></div>\n    <input id="homeAdId" type="hidden">\n    <label class="wenikFieldLabel">Banner image</label>\n    <div class="wenikUploadBox">\n      <input id="homeAdUpload" type="file" accept="image/*" class="wenikFileInput">\n      <button id="homeAdUploadBtn" class="btn secondary" type="button">UPLOAD IMAGE</button>\n      <div class="muted wenikHint">Images are displayed in one fixed dashboard size automatically.</div>\n      <img id="homeAdPreview" class="wenikDashPreview hidden" alt="Banner preview">\n    </div>\n    <details class="wenikAdvancedUrl"><summary>Or use image URL</summary><input id="homeAdImage" class="field" placeholder="https://..."></details>\n    <label class="wenikFieldLabel">Title <span class="muted">optional</span></label>\n    <input id="homeAdTitle" class="field" placeholder="Banner title">\n    <label class="wenikFieldLabel">When customer taps the banner</label>\n    <div class="two"><select id="homeAdCtaType" class="field"><option value="partner_page">Open Partner page</option><option value="url">Open URL</option><option value="none">No action</option></select><input id="homeAdCtaUrl" class="field" placeholder="URL or /path"></div>\n    <div class="wenikAdvancedGrid">\n      <label>Display order<input id="homeAdSort" class="field" type="number" value="100" placeholder="100"></label>\n      <label>Priority<input id="homeAdPriority" class="field" type="number" value="0" placeholder="0"></label>\n      <label>Starts at<input id="homeAdStart" class="field" type="datetime-local"></label>\n      <label>Ends at<input id="homeAdEnd" class="field" type="datetime-local"></label>\n    </div>\n    <label class="wenikFieldLabel">Status</label>\n    <select id="homeAdActive" class="field"><option value="true">Active · show on Customer Home</option><option value="false">Inactive · keep hidden</option></select>\n    <div class="actions"><button id="saveHomeAd" class="btn">SAVE BANNER</button><button id="clearHomeAd" class="btn secondary">CLEAR</button></div>\n    <div id="homeAdStatus" class="status"></div>\n  </div>\n  <h3 class="wenikSavedTitle">Current banners</h3>\n  <div id="homeAdsList"></div>\n</section>'''

if old not in s:
    raise SystemExit('dashboard section anchor missing')
s=s.replace(old,new,1)

css='''\n<style id="wenikAdminDashboardMobilePolishV1">\n/* WENIK ADMIN DASHBOARD MOBILE POLISH V1 */\n.wenikDashHead,.wenikDashEditor{max-width:760px;margin-left:auto;margin-right:auto}.wenikDashHead{padding:18px 20px}.wenikDashEditor{padding:20px}.wenikMiniBtn{width:auto!important;margin-top:0!important;padding:10px 14px!important}.wenikFieldLabel{display:block;font-size:12px;font-weight:900;color:#ddd6e8;margin:16px 0 4px}.wenikFieldLabel .muted{font-weight:600}.wenikUploadBox{border:1px dashed rgba(178,92,255,.42);border-radius:18px;padding:13px;background:rgba(255,255,255,.025)}.wenikFileInput{display:block;width:100%;color:#cfc7d9;margin-bottom:8px}.wenikHint{font-size:12px;line-height:1.35;margin-top:8px}.wenikDashPreview{width:100%;aspect-ratio:16/9;object-fit:cover;object-position:center;border-radius:16px;margin-top:12px;border:1px solid rgba(178,92,255,.22);background:#070610}.wenikAdvancedUrl{margin-top:10px}.wenikAdvancedUrl summary{cursor:pointer;color:#b9b4c8;font-size:12px;font-weight:800}.wenikAdvancedGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:8px}.wenikAdvancedGrid label{font-size:11px;font-weight:800;color:#aaa1b8}.wenikAdvancedGrid .field{margin-top:6px}.wenikSavedTitle{max-width:760px;margin:22px auto 8px}.wenikDashEditor .field,.wenikDashEditor select{min-height:50px}.wenikDashEditor .actions{margin-top:16px}@media(max-width:520px){.wenikDashHead,.wenikDashEditor{border-radius:22px;padding:16px}.wenikDashHead .row{align-items:center}.wenikDashHead h2{font-size:24px;margin-bottom:5px}.wenikDashEditor h3{font-size:22px}.wenikAdvancedGrid{grid-template-columns:1fr}.wenikMiniBtn{padding:9px 11px!important;font-size:12px!important}.wenikDashEditor .actions{grid-template-columns:1.35fr .65fr}.wenikDashEditor .field,.wenikDashEditor select{padding:13px 14px;margin-top:7px}}\n</style>\n'''
s=s.replace('</head>',css+'</head>',1)

js='''\n<script id="wenikAdminDashboardUploadV1">\n(function(){\n function el(id){return document.getElementById(id)}\n function showPreview(url){const p=el('homeAdPreview');if(!p)return;if(url){p.src=url;p.classList.remove('hidden')}else{p.removeAttribute('src');p.classList.add('hidden')}}\n function bind(){\n  const file=el('homeAdUpload'),btn=el('homeAdUploadBtn'),url=el('homeAdImage');if(!file||!btn||!url)return;\n  file.addEventListener('change',()=>{const f=file.files&&file.files[0];if(f)showPreview(URL.createObjectURL(f))});\n  url.addEventListener('input',()=>showPreview(url.value.trim()));\n  btn.addEventListener('click',async()=>{\n   const f=file.files&&file.files[0];if(!f){if(window.setStatus)setStatus('homeAdStatus','Choose an image first.');return}\n   if(!/^image\//.test(f.type)){if(window.setStatus)setStatus('homeAdStatus','Please choose an image file.');return}\n   if(f.size>8*1024*1024){if(window.setStatus)setStatus('homeAdStatus','Image is too large. Maximum 8 MB.');return}\n   const old=btn.textContent;btn.disabled=true;btn.textContent='UPLOADING...';\n   try{\n    const ext=(f.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase()||'jpg';\n    const path='home-dashboard/'+Date.now()+'-'+Math.random().toString(36).slice(2,8)+'.'+ext;\n    const r=await sb.storage.from('partner-media').upload(path,f,{cacheControl:'3600',upsert:false,contentType:f.type});\n    if(r.error)throw r.error;\n    const pub=sb.storage.from('partner-media').getPublicUrl(path);\n    const publicUrl=pub&&pub.data&&pub.data.publicUrl;if(!publicUrl)throw Error('Could not create image URL.');\n    url.value=publicUrl;showPreview(publicUrl);if(window.setStatus)setStatus('homeAdStatus','Image uploaded. Now press SAVE BANNER.',true);\n   }catch(e){if(window.setStatus)setStatus('homeAdStatus',(e&&e.message)||'Image upload failed. You can still use Image URL.')}finally{btn.disabled=false;btn.textContent=old}\n  });\n  const clear=el('clearHomeAd');if(clear)clear.addEventListener('click',()=>{file.value='';showPreview('')});\n }\n if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();\n})();\n</script>\n'''
s=s.replace('</body>',js+'</body>',1)
p.write_text(s,encoding='utf-8')
print('Admin Dashboard mobile polish applied')
