import { useState } from 'react';
import { Alert, Linking, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as Location from 'expo-location';
const places:[string,number,number][]=[['Beirut',33.8938,35.5018],['Dahieh',33.8442,35.5104],['Baabda',33.8339,35.5442],['Metn',33.8844,35.6334],['Jounieh',33.9808,35.6178],['Jbeil',34.1236,35.6511],['Aley',33.8104,35.5970],['Chouf',33.6977,35.5795],['Saida',33.5571,35.3729],['Tyre',33.2705,35.2038],['Jezzine',33.5417,35.5844],['Nabatieh',33.3772,35.4838],['Bint Jbeil',33.1199,35.4334],['Marjayoun',33.3603,35.5911],['Hasbaya',33.3983,35.6854],['Zahle',33.8463,35.9020],['Baalbek',34.0047,36.2110],['Hermel',34.3942,36.3840],['Tripoli',34.4367,35.8497],['Zgharta',34.3970,35.8950],['Batroun',34.2552,35.6581],['Bsharri',34.2508,36.0106],['Akkar',34.5428,36.0790]];
export default function AreaPicker({value,areas,onChange}:{value:string,areas:string[],onChange:(area:string)=>void}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[position,setPosition]=useState<Location.LocationObject|null>(null);
 const choices=Array.from(new Set([...places.map(x=>x[0]),...areas])).sort();
 async function locate(){if(busy)return;setBusy(true);try{const p=await Location.requestForegroundPermissionsAsync();if(!p.granted){Alert.alert('WENIK','Allow location access or choose your area below.');return;}const result=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});setPosition(result);const {latitude,longitude}=result.coords;const distance=(x:typeof places[number])=>Math.hypot((x[1]-latitude)*111,(x[2]-longitude)*111*Math.cos(latitude*Math.PI/180));const nearest=[...places].sort((a,b)=>distance(a)-distance(b))[0];if(distance(nearest)>60){Alert.alert('WENIK','Choose your area manually. Your location is outside the listed areas.');return;}onChange(nearest[0]);Alert.alert('Nearby area',`${nearest[0]} selected. You can choose another area below.`);}catch{Alert.alert('WENIK','Could not find your location. Check location settings or choose an area.');}finally{setBusy(false)}}
 return <><Pressable accessibilityRole="button" onPress={()=>setOpen(true)} style={s.button}><Text style={s.label}>📍 {value&&value!=='All'?value:'Choose location'} ▾</Text></Pressable><Modal visible={open} animationType="slide" onRequestClose={()=>setOpen(false)}><SafeAreaView style={s.safe}><Pressable onPress={()=>setOpen(false)} style={s.button}><Text style={s.label}>CLOSE ×</Text></Pressable><Text style={s.title}>Choose your area</Text><Pressable disabled={busy} onPress={locate} style={s.button}><Text style={s.label}>{busy?'Finding your location…':'USE MY LOCATION'}</Text></Pressable>{position?<Pressable style={s.button} onPress={()=>Linking.openURL(`https://www.google.com/maps/search/?api=1&query=${position.coords.latitude},${position.coords.longitude}`).catch(()=>Alert.alert('WENIK','Could not open the map.'))}><Text style={s.label}>VIEW MY LOCATION ON MAP →</Text></Pressable>:null}<TextInput value={query} onChangeText={setQuery} placeholder="Search area" style={s.input}/><ScrollView keyboardShouldPersistTaps="handled"><Pressable style={s.button} onPress={()=>{onChange('All');setOpen(false)}}><Text style={s.label}>All areas</Text></Pressable>{choices.filter(x=>x.toLowerCase().includes(query.trim().toLowerCase())).map(x=><Pressable key={x} style={s.button} onPress={()=>{onChange(x);setOpen(false)}}><Text style={s.label}>{x}{value===x?' ✓':''}</Text></Pressable>)}</ScrollView></SafeAreaView></Modal></>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8f7fb',padding:18},button:{backgroundColor:'#fff',padding:14,borderRadius:16,marginVertical:4,borderWidth:1,borderColor:'#ddd0ee'},label:{color:'#6723ba',fontSize:13,fontWeight:'800'},title:{fontSize:24,fontWeight:'900',color:'#18141d',marginVertical:16},input:{backgroundColor:'#fff',padding:14,borderRadius:16,marginVertical:12,color:'#18141d'}});
